
package gov.va.medora.mdws.emrsvc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 05 13:15:55 MST 2011
 * Generated source version: 2.1.3
 * 
 */

public final class EmrSvcSoap_EmrSvcSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://mdws.medora.va.gov/EmrSvc", "EmrSvc");

    private EmrSvcSoap_EmrSvcSoap_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = EmrSvc.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        EmrSvc ss = new EmrSvc(wsdlURL, SERVICE_NAME);
        EmrSvcSoap port = ss.getEmrSvcSoap();  
        
        {
        System.out.println("Invoking getWards...");
        gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray _getWards__return = port.getWards();
        System.out.println("getWards.result=" + _getWards__return);


        }
        {
        System.out.println("Invoking getRadiologyReports...");
        java.lang.String _getRadiologyReports_fromDate = "";
        java.lang.String _getRadiologyReports_toDate = "";
        int _getRadiologyReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedRadiologyReportArrays _getRadiologyReports__return = port.getRadiologyReports(_getRadiologyReports_fromDate, _getRadiologyReports_toDate, _getRadiologyReports_nrpts);
        System.out.println("getRadiologyReports.result=" + _getRadiologyReports__return);


        }
        {
        System.out.println("Invoking getCytologyReports...");
        java.lang.String _getCytologyReports_fromDate = "";
        java.lang.String _getCytologyReports_toDate = "";
        int _getCytologyReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedCytologyRptArrays _getCytologyReports__return = port.getCytologyReports(_getCytologyReports_fromDate, _getCytologyReports_toDate, _getCytologyReports_nrpts);
        System.out.println("getCytologyReports.result=" + _getCytologyReports__return);


        }
        {
        System.out.println("Invoking getVisits...");
        java.lang.String _getVisits_fromDate = "";
        java.lang.String _getVisits_toDate = "";
        gov.va.medora.mdws.emrsvc.TaggedVisitArray _getVisits__return = port.getVisits(_getVisits_fromDate, _getVisits_toDate);
        System.out.println("getVisits.result=" + _getVisits__return);


        }
        {
        System.out.println("Invoking getCrisisNotes...");
        java.lang.String _getCrisisNotes_fromDate = "";
        java.lang.String _getCrisisNotes_toDate = "";
        int _getCrisisNotes_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getCrisisNotes__return = port.getCrisisNotes(_getCrisisNotes_fromDate, _getCrisisNotes_toDate, _getCrisisNotes_nrpts);
        System.out.println("getCrisisNotes.result=" + _getCrisisNotes__return);


        }
        {
        System.out.println("Invoking getSurgeryReports...");
        gov.va.medora.mdws.emrsvc.TaggedSurgeryReportArrays _getSurgeryReports__return = port.getSurgeryReports();
        System.out.println("getSurgeryReports.result=" + _getSurgeryReports__return);


        }
        {
        System.out.println("Invoking getIvMeds...");
        gov.va.medora.mdws.emrsvc.TaggedMedicationArrays _getIvMeds__return = port.getIvMeds();
        System.out.println("getIvMeds.result=" + _getIvMeds__return);


        }
        {
        System.out.println("Invoking getAllOrders...");
        gov.va.medora.mdws.emrsvc.TaggedOrderArrays _getAllOrders__return = port.getAllOrders();
        System.out.println("getAllOrders.result=" + _getAllOrders__return);


        }
        {
        System.out.println("Invoking getConfidentiality...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getConfidentiality__return = port.getConfidentiality();
        System.out.println("getConfidentiality.result=" + _getConfidentiality__return);


        }
        {
        System.out.println("Invoking getSurgeryReportsWithText...");
        gov.va.medora.mdws.emrsvc.TaggedSurgeryReportArrays _getSurgeryReportsWithText__return = port.getSurgeryReportsWithText();
        System.out.println("getSurgeryReportsWithText.result=" + _getSurgeryReportsWithText__return);


        }
        {
        System.out.println("Invoking getVitalSigns...");
        gov.va.medora.mdws.emrsvc.TaggedVitalSignSetArrays _getVitalSigns__return = port.getVitalSigns();
        System.out.println("getVitalSigns.result=" + _getVitalSigns__return);


        }
        {
        System.out.println("Invoking getChemHemReports...");
        java.lang.String _getChemHemReports_fromDate = "";
        java.lang.String _getChemHemReports_toDate = "";
        int _getChemHemReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedChemHemRptArrays _getChemHemReports__return = port.getChemHemReports(_getChemHemReports_fromDate, _getChemHemReports_toDate, _getChemHemReports_nrpts);
        System.out.println("getChemHemReports.result=" + _getChemHemReports__return);


        }
        {
        System.out.println("Invoking getMedsAdminHx...");
        java.lang.String _getMedsAdminHx_fromDate = "";
        java.lang.String _getMedsAdminHx_toDate = "";
        int _getMedsAdminHx_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getMedsAdminHx__return = port.getMedsAdminHx(_getMedsAdminHx_fromDate, _getMedsAdminHx_toDate, _getMedsAdminHx_nrpts);
        System.out.println("getMedsAdminHx.result=" + _getMedsAdminHx__return);


        }
        {
        System.out.println("Invoking getImmunizations...");
        java.lang.String _getImmunizations_fromDate = "";
        java.lang.String _getImmunizations_toDate = "";
        int _getImmunizations_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getImmunizations__return = port.getImmunizations(_getImmunizations_fromDate, _getImmunizations_toDate, _getImmunizations_nrpts);
        System.out.println("getImmunizations.result=" + _getImmunizations__return);


        }
        {
        System.out.println("Invoking closeNote...");
        java.lang.String _closeNote_noteIEN = "";
        java.lang.String _closeNote_consultIEN = "";
        gov.va.medora.mdws.emrsvc.TextTO _closeNote__return = port.closeNote(_closeNote_noteIEN, _closeNote_consultIEN);
        System.out.println("closeNote.result=" + _closeNote__return);


        }
        {
        System.out.println("Invoking select...");
        java.lang.String _select_dfn = "";
        gov.va.medora.mdws.emrsvc.PatientTO _select__return = port.select(_select_dfn);
        System.out.println("select.result=" + _select__return);


        }
        {
        System.out.println("Invoking getProblemList...");
        java.lang.String _getProblemList_type = "";
        gov.va.medora.mdws.emrsvc.TaggedProblemArrays _getProblemList__return = port.getProblemList(_getProblemList_type);
        System.out.println("getProblemList.result=" + _getProblemList__return);


        }
        {
        System.out.println("Invoking getSurgicalPathologyReports...");
        java.lang.String _getSurgicalPathologyReports_fromDate = "";
        java.lang.String _getSurgicalPathologyReports_toDate = "";
        int _getSurgicalPathologyReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedSurgicalPathologyRptArrays _getSurgicalPathologyReports__return = port.getSurgicalPathologyReports(_getSurgicalPathologyReports_fromDate, _getSurgicalPathologyReports_toDate, _getSurgicalPathologyReports_nrpts);
        System.out.println("getSurgicalPathologyReports.result=" + _getSurgicalPathologyReports__return);


        }
        {
        System.out.println("Invoking getMicrobiologyReports...");
        java.lang.String _getMicrobiologyReports_fromDate = "";
        java.lang.String _getMicrobiologyReports_toDate = "";
        int _getMicrobiologyReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedMicrobiologyRptArrays _getMicrobiologyReports__return = port.getMicrobiologyReports(_getMicrobiologyReports_fromDate, _getMicrobiologyReports_toDate, _getMicrobiologyReports_nrpts);
        System.out.println("getMicrobiologyReports.result=" + _getMicrobiologyReports__return);


        }
        {
        System.out.println("Invoking getExpandedAdtReports...");
        java.lang.String _getExpandedAdtReports_fromDate = "";
        java.lang.String _getExpandedAdtReports_toDate = "";
        int _getExpandedAdtReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getExpandedAdtReports__return = port.getExpandedAdtReports(_getExpandedAdtReports_fromDate, _getExpandedAdtReports_toDate, _getExpandedAdtReports_nrpts);
        System.out.println("getExpandedAdtReports.result=" + _getExpandedAdtReports__return);


        }
        {
        System.out.println("Invoking getIcdProceduresReports...");
        java.lang.String _getIcdProceduresReports_fromDate = "";
        java.lang.String _getIcdProceduresReports_toDate = "";
        int _getIcdProceduresReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedIcdRptArrays _getIcdProceduresReports__return = port.getIcdProceduresReports(_getIcdProceduresReports_fromDate, _getIcdProceduresReports_toDate, _getIcdProceduresReports_nrpts);
        System.out.println("getIcdProceduresReports.result=" + _getIcdProceduresReports__return);


        }
        {
        System.out.println("Invoking getAllMeds...");
        gov.va.medora.mdws.emrsvc.TaggedMedicationArrays _getAllMeds__return = port.getAllMeds();
        System.out.println("getAllMeds.result=" + _getAllMeds__return);


        }
        {
        System.out.println("Invoking cprsUserLookup...");
        java.lang.String _cprsUserLookup_target = "";
        gov.va.medora.mdws.emrsvc.UserArray _cprsUserLookup__return = port.cprsUserLookup(_cprsUserLookup_target);
        System.out.println("cprsUserLookup.result=" + _cprsUserLookup__return);


        }
        {
        System.out.println("Invoking getMedsAdminLog...");
        java.lang.String _getMedsAdminLog_fromDate = "";
        java.lang.String _getMedsAdminLog_toDate = "";
        int _getMedsAdminLog_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getMedsAdminLog__return = port.getMedsAdminLog(_getMedsAdminLog_fromDate, _getMedsAdminLog_toDate, _getMedsAdminLog_nrpts);
        System.out.println("getMedsAdminLog.result=" + _getMedsAdminLog__return);


        }
        {
        System.out.println("Invoking visit...");
        java.lang.String _visit_pwd = "";
        java.lang.String _visit_sitelist = "";
        java.lang.String _visit_userSitecode = "";
        java.lang.String _visit_userName = "";
        java.lang.String _visit_duz = "";
        java.lang.String _visit_ssn = "";
        java.lang.String _visit_context = "";
        gov.va.medora.mdws.emrsvc.TaggedTextArray _visit__return = port.visit(_visit_pwd, _visit_sitelist, _visit_userSitecode, _visit_userName, _visit_duz, _visit_ssn, _visit_context);
        System.out.println("visit.result=" + _visit__return);


        }
        {
        System.out.println("Invoking getTreatingSpecialtyReports...");
        java.lang.String _getTreatingSpecialtyReports_fromDate = "";
        java.lang.String _getTreatingSpecialtyReports_toDate = "";
        int _getTreatingSpecialtyReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getTreatingSpecialtyReports__return = port.getTreatingSpecialtyReports(_getTreatingSpecialtyReports_fromDate, _getTreatingSpecialtyReports_toDate, _getTreatingSpecialtyReports_nrpts);
        System.out.println("getTreatingSpecialtyReports.result=" + _getTreatingSpecialtyReports__return);


        }
        {
        System.out.println("Invoking setupMultiSiteQuery...");
        java.lang.String _setupMultiSiteQuery_appPwd = "";
        gov.va.medora.mdws.emrsvc.SiteArray _setupMultiSiteQuery__return = port.setupMultiSiteQuery(_setupMultiSiteQuery_appPwd);
        System.out.println("setupMultiSiteQuery.result=" + _setupMultiSiteQuery__return);


        }
        {
        System.out.println("Invoking getLocations...");
        java.lang.String _getLocations_target = "";
        java.lang.String _getLocations_direction = "";
        gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray _getLocations__return = port.getLocations(_getLocations_target, _getLocations_direction);
        System.out.println("getLocations.result=" + _getLocations__return);


        }
        {
        System.out.println("Invoking getFutureClinicVisitsReports...");
        java.lang.String _getFutureClinicVisitsReports_fromDate = "";
        java.lang.String _getFutureClinicVisitsReports_toDate = "";
        int _getFutureClinicVisitsReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getFutureClinicVisitsReports__return = port.getFutureClinicVisitsReports(_getFutureClinicVisitsReports_fromDate, _getFutureClinicVisitsReports_toDate, _getFutureClinicVisitsReports_nrpts);
        System.out.println("getFutureClinicVisitsReports.result=" + _getFutureClinicVisitsReports__return);


        }
        {
        System.out.println("Invoking isOneVisitNote...");
        java.lang.String _isOneVisitNote_noteDefinitionIEN = "";
        java.lang.String _isOneVisitNote_noteTitle = "";
        java.lang.String _isOneVisitNote_visitString = "";
        gov.va.medora.mdws.emrsvc.TaggedText _isOneVisitNote__return = port.isOneVisitNote(_isOneVisitNote_noteDefinitionIEN, _isOneVisitNote_noteTitle, _isOneVisitNote_visitString);
        System.out.println("isOneVisitNote.result=" + _isOneVisitNote__return);


        }
        {
        System.out.println("Invoking isCosignerRequired...");
        java.lang.String _isCosignerRequired_noteDefinitionIEN = "";
        java.lang.String _isCosignerRequired_authorDUZ = "";
        gov.va.medora.mdws.emrsvc.TextTO _isCosignerRequired__return = port.isCosignerRequired(_isCosignerRequired_noteDefinitionIEN, _isCosignerRequired_authorDUZ);
        System.out.println("isCosignerRequired.result=" + _isCosignerRequired__return);


        }
        {
        System.out.println("Invoking getCytopathologyReports...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getCytopathologyReports__return = port.getCytopathologyReports();
        System.out.println("getCytopathologyReports.result=" + _getCytopathologyReports__return);


        }
        {
        System.out.println("Invoking getSurgeryReportText...");
        java.lang.String _getSurgeryReportText_siteId = "";
        java.lang.String _getSurgeryReportText_rptId = "";
        gov.va.medora.mdws.emrsvc.TextTO _getSurgeryReportText__return = port.getSurgeryReportText(_getSurgeryReportText_siteId, _getSurgeryReportText_rptId);
        System.out.println("getSurgeryReportText.result=" + _getSurgeryReportText__return);


        }
        {
        System.out.println("Invoking getElectronMicroscopyReports...");
        java.lang.String _getElectronMicroscopyReports_fromDate = "";
        java.lang.String _getElectronMicroscopyReports_toDate = "";
        int _getElectronMicroscopyReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getElectronMicroscopyReports__return = port.getElectronMicroscopyReports(_getElectronMicroscopyReports_fromDate, _getElectronMicroscopyReports_toDate, _getElectronMicroscopyReports_nrpts);
        System.out.println("getElectronMicroscopyReports.result=" + _getElectronMicroscopyReports__return);


        }
        {
        System.out.println("Invoking isValidEsig...");
        java.lang.String _isValidEsig_esig = "";
        gov.va.medora.mdws.emrsvc.TextTO _isValidEsig__return = port.isValidEsig(_isValidEsig_esig);
        System.out.println("isValidEsig.result=" + _isValidEsig__return);


        }
        {
        System.out.println("Invoking issueConfidentialityBulletin...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _issueConfidentialityBulletin__return = port.issueConfidentialityBulletin();
        System.out.println("issueConfidentialityBulletin.result=" + _issueConfidentialityBulletin__return);


        }
        {
        System.out.println("Invoking getDischargesReports...");
        java.lang.String _getDischargesReports_fromDate = "";
        java.lang.String _getDischargesReports_toDate = "";
        int _getDischargesReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getDischargesReports__return = port.getDischargesReports(_getDischargesReports_fromDate, _getDischargesReports_toDate, _getDischargesReports_nrpts);
        System.out.println("getDischargesReports.result=" + _getDischargesReports__return);


        }
        {
        System.out.println("Invoking getMedicationDetail...");
        java.lang.String _getMedicationDetail_siteId = "";
        java.lang.String _getMedicationDetail_medId = "";
        gov.va.medora.mdws.emrsvc.TextTO _getMedicationDetail__return = port.getMedicationDetail(_getMedicationDetail_siteId, _getMedicationDetail_medId);
        System.out.println("getMedicationDetail.result=" + _getMedicationDetail__return);


        }
        {
        System.out.println("Invoking getOutpatientEncounterReports...");
        java.lang.String _getOutpatientEncounterReports_fromDate = "";
        java.lang.String _getOutpatientEncounterReports_toDate = "";
        int _getOutpatientEncounterReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getOutpatientEncounterReports__return = port.getOutpatientEncounterReports(_getOutpatientEncounterReports_fromDate, _getOutpatientEncounterReports_toDate, _getOutpatientEncounterReports_nrpts);
        System.out.println("getOutpatientEncounterReports.result=" + _getOutpatientEncounterReports__return);


        }
        {
        System.out.println("Invoking getBloodTransfusionReports...");
        java.lang.String _getBloodTransfusionReports_fromDate = "";
        java.lang.String _getBloodTransfusionReports_toDate = "";
        int _getBloodTransfusionReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getBloodTransfusionReports__return = port.getBloodTransfusionReports(_getBloodTransfusionReports_fromDate, _getBloodTransfusionReports_toDate, _getBloodTransfusionReports_nrpts);
        System.out.println("getBloodTransfusionReports.result=" + _getBloodTransfusionReports__return);


        }
        {
        System.out.println("Invoking getClinics...");
        java.lang.String _getClinics_target = "";
        gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray _getClinics__return = port.getClinics(_getClinics_target);
        System.out.println("getClinics.result=" + _getClinics__return);


        }
        {
        System.out.println("Invoking getPatientsByWard...");
        java.lang.String _getPatientsByWard_wardId = "";
        gov.va.medora.mdws.emrsvc.TaggedPatientArray _getPatientsByWard__return = port.getPatientsByWard(_getPatientsByWard_wardId);
        System.out.println("getPatientsByWard.result=" + _getPatientsByWard__return);


        }
        {
        System.out.println("Invoking nptLookup...");
        java.lang.String _nptLookup_ssn = "";
        gov.va.medora.mdws.emrsvc.PatientArray _nptLookup__return = port.nptLookup(_nptLookup_ssn);
        System.out.println("nptLookup.result=" + _nptLookup__return);


        }
        {
        System.out.println("Invoking getDischargeSummaries...");
        java.lang.String _getDischargeSummaries_fromDate = "";
        java.lang.String _getDischargeSummaries_toDate = "";
        int _getDischargeSummaries_nNotes = 0;
        gov.va.medora.mdws.emrsvc.TaggedNoteArrays _getDischargeSummaries__return = port.getDischargeSummaries(_getDischargeSummaries_fromDate, _getDischargeSummaries_toDate, _getDischargeSummaries_nNotes);
        System.out.println("getDischargeSummaries.result=" + _getDischargeSummaries__return);


        }
        {
        System.out.println("Invoking getVHA...");
        gov.va.medora.mdws.emrsvc.RegionArray _getVHA__return = port.getVHA();
        System.out.println("getVHA.result=" + _getVHA__return);


        }
        {
        System.out.println("Invoking getPrfNoteActions...");
        java.lang.String _getPrfNoteActions_noteDefinitionIEN = "";
        gov.va.medora.mdws.emrsvc.PatientRecordFlagArray _getPrfNoteActions__return = port.getPrfNoteActions(_getPrfNoteActions_noteDefinitionIEN);
        System.out.println("getPrfNoteActions.result=" + _getPrfNoteActions__return);


        }
        {
        System.out.println("Invoking getPastClinicVisitsReports...");
        java.lang.String _getPastClinicVisitsReports_fromDate = "";
        java.lang.String _getPastClinicVisitsReports_toDate = "";
        int _getPastClinicVisitsReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getPastClinicVisitsReports__return = port.getPastClinicVisitsReports(_getPastClinicVisitsReports_fromDate, _getPastClinicVisitsReports_toDate, _getPastClinicVisitsReports_nrpts);
        System.out.println("getPastClinicVisitsReports.result=" + _getPastClinicVisitsReports__return);


        }
        {
        System.out.println("Invoking isSurgeryNote...");
        java.lang.String _isSurgeryNote_noteDefinitionIEN = "";
        gov.va.medora.mdws.emrsvc.TaggedText _isSurgeryNote__return = port.isSurgeryNote(_isSurgeryNote_noteDefinitionIEN);
        System.out.println("isSurgeryNote.result=" + _isSurgeryNote__return);


        }
        {
        System.out.println("Invoking patientInquiry...");
        gov.va.medora.mdws.emrsvc.TextTO _patientInquiry__return = port.patientInquiry();
        System.out.println("patientInquiry.result=" + _patientInquiry__return);


        }
        {
        System.out.println("Invoking getOtherMeds...");
        gov.va.medora.mdws.emrsvc.TaggedMedicationArrays _getOtherMeds__return = port.getOtherMeds();
        System.out.println("getOtherMeds.result=" + _getOtherMeds__return);


        }
        {
        System.out.println("Invoking getBloodBankReports...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getBloodBankReports__return = port.getBloodBankReports();
        System.out.println("getBloodBankReports.result=" + _getBloodBankReports__return);


        }
        {
        System.out.println("Invoking getFacadeVersion...");
        gov.va.medora.mdws.emrsvc.TextTO _getFacadeVersion__return = port.getFacadeVersion();
        System.out.println("getFacadeVersion.result=" + _getFacadeVersion__return);


        }
        {
        System.out.println("Invoking getAllergies...");
        gov.va.medora.mdws.emrsvc.TaggedAllergyArrays _getAllergies__return = port.getAllergies();
        System.out.println("getAllergies.result=" + _getAllergies__return);


        }
        {
        System.out.println("Invoking getVersion...");
        java.lang.String _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking getNoteTitles...");
        java.lang.String _getNoteTitles_target = "";
        java.lang.String _getNoteTitles_direction = "";
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getNoteTitles__return = port.getNoteTitles(_getNoteTitles_target, _getNoteTitles_direction);
        System.out.println("getNoteTitles.result=" + _getNoteTitles__return);


        }
        {
        System.out.println("Invoking getAppointmentText...");
        java.lang.String _getAppointmentText_siteId = "";
        java.lang.String _getAppointmentText_apptId = "";
        gov.va.medora.mdws.emrsvc.TextTO _getAppointmentText__return = port.getAppointmentText(_getAppointmentText_siteId, _getAppointmentText_apptId);
        System.out.println("getAppointmentText.result=" + _getAppointmentText__return);


        }
        {
        System.out.println("Invoking getSpecialties...");
        gov.va.medora.mdws.emrsvc.TaggedText _getSpecialties__return = port.getSpecialties();
        System.out.println("getSpecialties.result=" + _getSpecialties__return);


        }
        {
        System.out.println("Invoking writeSimpleOrderByPolicy...");
        java.lang.String _writeSimpleOrderByPolicy_providerDUZ = "";
        java.lang.String _writeSimpleOrderByPolicy_esig = "";
        java.lang.String _writeSimpleOrderByPolicy_locationIEN = "";
        java.lang.String _writeSimpleOrderByPolicy_orderIEN = "";
        java.lang.String _writeSimpleOrderByPolicy_startDate = "";
        gov.va.medora.mdws.emrsvc.OrderTO _writeSimpleOrderByPolicy__return = port.writeSimpleOrderByPolicy(_writeSimpleOrderByPolicy_providerDUZ, _writeSimpleOrderByPolicy_esig, _writeSimpleOrderByPolicy_locationIEN, _writeSimpleOrderByPolicy_orderIEN, _writeSimpleOrderByPolicy_startDate);
        System.out.println("writeSimpleOrderByPolicy.result=" + _writeSimpleOrderByPolicy__return);


        }
        {
        System.out.println("Invoking getConsultsForPatient...");
        gov.va.medora.mdws.emrsvc.TaggedConsultArrays _getConsultsForPatient__return = port.getConsultsForPatient();
        System.out.println("getConsultsForPatient.result=" + _getConsultsForPatient__return);


        }
        {
        System.out.println("Invoking writeNote...");
        java.lang.String _writeNote_titleIEN = "";
        java.lang.String _writeNote_encounterString = "";
        java.lang.String _writeNote_text = "";
        java.lang.String _writeNote_authorDUZ = "";
        java.lang.String _writeNote_cosignerDUZ = "";
        java.lang.String _writeNote_consultIEN = "";
        java.lang.String _writeNote_prfIEN = "";
        gov.va.medora.mdws.emrsvc.NoteResultTO _writeNote__return = port.writeNote(_writeNote_titleIEN, _writeNote_encounterString, _writeNote_text, _writeNote_authorDUZ, _writeNote_cosignerDUZ, _writeNote_consultIEN, _writeNote_prfIEN);
        System.out.println("writeNote.result=" + _writeNote__return);


        }
        {
        System.out.println("Invoking getNotesWithText...");
        java.lang.String _getNotesWithText_fromDate = "";
        java.lang.String _getNotesWithText_toDate = "";
        int _getNotesWithText_nNotes = 0;
        gov.va.medora.mdws.emrsvc.TaggedNoteArrays _getNotesWithText__return = port.getNotesWithText(_getNotesWithText_fromDate, _getNotesWithText_toDate, _getNotesWithText_nNotes);
        System.out.println("getNotesWithText.result=" + _getNotesWithText__return);


        }
        {
        System.out.println("Invoking getBloodAvailabilityReports...");
        java.lang.String _getBloodAvailabilityReports_fromDate = "";
        java.lang.String _getBloodAvailabilityReports_toDate = "";
        int _getBloodAvailabilityReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getBloodAvailabilityReports__return = port.getBloodAvailabilityReports(_getBloodAvailabilityReports_fromDate, _getBloodAvailabilityReports_toDate, _getBloodAvailabilityReports_nrpts);
        System.out.println("getBloodAvailabilityReports.result=" + _getBloodAvailabilityReports__return);


        }
        {
        System.out.println("Invoking isPrfNote...");
        java.lang.String _isPrfNote_noteDefinitionIEN = "";
        gov.va.medora.mdws.emrsvc.TextTO _isPrfNote__return = port.isPrfNote(_isPrfNote_noteDefinitionIEN);
        System.out.println("isPrfNote.result=" + _isPrfNote__return);


        }
        {
        System.out.println("Invoking addDataSource...");
        java.lang.String _addDataSource_id = "";
        java.lang.String _addDataSource_name = "";
        java.lang.String _addDataSource_datasource = "";
        java.lang.String _addDataSource_port = "";
        java.lang.String _addDataSource_modality = "";
        java.lang.String _addDataSource_protocol = "";
        java.lang.String _addDataSource_region = "";
        gov.va.medora.mdws.emrsvc.SiteTO _addDataSource__return = port.addDataSource(_addDataSource_id, _addDataSource_name, _addDataSource_datasource, _addDataSource_port, _addDataSource_modality, _addDataSource_protocol, _addDataSource_region);
        System.out.println("addDataSource.result=" + _addDataSource__return);


        }
        {
        System.out.println("Invoking getCareTeamReports...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getCareTeamReports__return = port.getCareTeamReports();
        System.out.println("getCareTeamReports.result=" + _getCareTeamReports__return);


        }
        {
        System.out.println("Invoking getImoMeds...");
        gov.va.medora.mdws.emrsvc.TaggedMedicationArrays _getImoMeds__return = port.getImoMeds();
        System.out.println("getImoMeds.result=" + _getImoMeds__return);


        }
        {
        System.out.println("Invoking getIcdSurgeryReports...");
        java.lang.String _getIcdSurgeryReports_fromDate = "";
        java.lang.String _getIcdSurgeryReports_toDate = "";
        int _getIcdSurgeryReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedIcdRptArrays _getIcdSurgeryReports__return = port.getIcdSurgeryReports(_getIcdSurgeryReports_fromDate, _getIcdSurgeryReports_toDate, _getIcdSurgeryReports_nrpts);
        System.out.println("getIcdSurgeryReports.result=" + _getIcdSurgeryReports__return);


        }
        {
        System.out.println("Invoking getDischargeDiagnosisReports...");
        java.lang.String _getDischargeDiagnosisReports_fromDate = "";
        java.lang.String _getDischargeDiagnosisReports_toDate = "";
        int _getDischargeDiagnosisReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getDischargeDiagnosisReports__return = port.getDischargeDiagnosisReports(_getDischargeDiagnosisReports_fromDate, _getDischargeDiagnosisReports_toDate, _getDischargeDiagnosisReports_nrpts);
        System.out.println("getDischargeDiagnosisReports.result=" + _getDischargeDiagnosisReports__return);


        }
        {
        System.out.println("Invoking connect...");
        java.lang.String _connect_sitelist = "";
        gov.va.medora.mdws.emrsvc.DataSourceArray _connect__return = port.connect(_connect_sitelist);
        System.out.println("connect.result=" + _connect__return);


        }
        {
        System.out.println("Invoking getAutopsyReports...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getAutopsyReports__return = port.getAutopsyReports();
        System.out.println("getAutopsyReports.result=" + _getAutopsyReports__return);


        }
        {
        System.out.println("Invoking getUnsignedNotes...");
        java.lang.String _getUnsignedNotes_fromDate = "";
        java.lang.String _getUnsignedNotes_toDate = "";
        int _getUnsignedNotes_nNotes = 0;
        gov.va.medora.mdws.emrsvc.TaggedNoteArrays _getUnsignedNotes__return = port.getUnsignedNotes(_getUnsignedNotes_fromDate, _getUnsignedNotes_toDate, _getUnsignedNotes_nNotes);
        System.out.println("getUnsignedNotes.result=" + _getUnsignedNotes__return);


        }
        {
        System.out.println("Invoking getAppointments...");
        gov.va.medora.mdws.emrsvc.TaggedAppointmentArrays _getAppointments__return = port.getAppointments();
        System.out.println("getAppointments.result=" + _getAppointments__return);


        }
        {
        System.out.println("Invoking getUnitDoseMeds...");
        gov.va.medora.mdws.emrsvc.TaggedMedicationArrays _getUnitDoseMeds__return = port.getUnitDoseMeds();
        System.out.println("getUnitDoseMeds.result=" + _getUnitDoseMeds__return);


        }
        {
        System.out.println("Invoking getAdmissions...");
        gov.va.medora.mdws.emrsvc.TaggedInpatientStayArray _getAdmissions__return = port.getAdmissions();
        System.out.println("getAdmissions.result=" + _getAdmissions__return);


        }
        {
        System.out.println("Invoking getPatientsBySpecialty...");
        java.lang.String _getPatientsBySpecialty_specialtyId = "";
        gov.va.medora.mdws.emrsvc.TaggedPatientArray _getPatientsBySpecialty__return = port.getPatientsBySpecialty(_getPatientsBySpecialty_specialtyId);
        System.out.println("getPatientsBySpecialty.result=" + _getPatientsBySpecialty__return);


        }
        {
        System.out.println("Invoking getDemographics...");
        gov.va.medora.mdws.emrsvc.PatientTO _getDemographics__return = port.getDemographics();
        System.out.println("getDemographics.result=" + _getDemographics__return);


        }
        {
        System.out.println("Invoking getHospitalLocations...");
        java.lang.String _getHospitalLocations_target = "";
        java.lang.String _getHospitalLocations_direction = "";
        gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray _getHospitalLocations__return = port.getHospitalLocations(_getHospitalLocations_target, _getHospitalLocations_direction);
        System.out.println("getHospitalLocations.result=" + _getHospitalLocations__return);


        }
        {
        System.out.println("Invoking getCompAndPenReports...");
        java.lang.String _getCompAndPenReports_fromDate = "";
        java.lang.String _getCompAndPenReports_toDate = "";
        int _getCompAndPenReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getCompAndPenReports__return = port.getCompAndPenReports(_getCompAndPenReports_fromDate, _getCompAndPenReports_toDate, _getCompAndPenReports_nrpts);
        System.out.println("getCompAndPenReports.result=" + _getCompAndPenReports__return);


        }
        {
        System.out.println("Invoking getNote...");
        java.lang.String _getNote_siteId = "";
        java.lang.String _getNote_noteId = "";
        gov.va.medora.mdws.emrsvc.TextTO _getNote__return = port.getNote(_getNote_siteId, _getNote_noteId);
        System.out.println("getNote.result=" + _getNote__return);


        }
        {
        System.out.println("Invoking getLatestVitalSigns...");
        gov.va.medora.mdws.emrsvc.TaggedVitalSignArrays _getLatestVitalSigns__return = port.getLatestVitalSigns();
        System.out.println("getLatestVitalSigns.result=" + _getLatestVitalSigns__return);


        }
        {
        System.out.println("Invoking match...");
        java.lang.String _match_target = "";
        gov.va.medora.mdws.emrsvc.TaggedPatientArrays _match__return = port.match(_match_target);
        System.out.println("match.result=" + _match__return);


        }
        {
        System.out.println("Invoking isConsultNote...");
        java.lang.String _isConsultNote_noteDefinitionIEN = "";
        gov.va.medora.mdws.emrsvc.TextTO _isConsultNote__return = port.isConsultNote(_isConsultNote_noteDefinitionIEN);
        System.out.println("isConsultNote.result=" + _isConsultNote__return);


        }
        {
        System.out.println("Invoking disconnectRemoteSites...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _disconnectRemoteSites__return = port.disconnectRemoteSites();
        System.out.println("disconnectRemoteSites.result=" + _disconnectRemoteSites__return);


        }
        {
        System.out.println("Invoking getClinicalWarnings...");
        java.lang.String _getClinicalWarnings_fromDate = "";
        java.lang.String _getClinicalWarnings_toDate = "";
        int _getClinicalWarnings_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getClinicalWarnings__return = port.getClinicalWarnings(_getClinicalWarnings_fromDate, _getClinicalWarnings_toDate, _getClinicalWarnings_nrpts);
        System.out.println("getClinicalWarnings.result=" + _getClinicalWarnings__return);


        }
        {
        System.out.println("Invoking disconnect...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _disconnect__return = port.disconnect();
        System.out.println("disconnect.result=" + _disconnect__return);


        }
        {
        System.out.println("Invoking getUncosignedNotes...");
        java.lang.String _getUncosignedNotes_fromDate = "";
        java.lang.String _getUncosignedNotes_toDate = "";
        int _getUncosignedNotes_nNotes = 0;
        gov.va.medora.mdws.emrsvc.TaggedNoteArrays _getUncosignedNotes__return = port.getUncosignedNotes(_getUncosignedNotes_fromDate, _getUncosignedNotes_toDate, _getUncosignedNotes_nNotes);
        System.out.println("getUncosignedNotes.result=" + _getUncosignedNotes__return);


        }
        {
        System.out.println("Invoking getOutpatientMeds...");
        gov.va.medora.mdws.emrsvc.TaggedMedicationArrays _getOutpatientMeds__return = port.getOutpatientMeds();
        System.out.println("getOutpatientMeds.result=" + _getOutpatientMeds__return);


        }
        {
        System.out.println("Invoking getPatientsByTeam...");
        java.lang.String _getPatientsByTeam_teamId = "";
        gov.va.medora.mdws.emrsvc.TaggedPatientArray _getPatientsByTeam__return = port.getPatientsByTeam(_getPatientsByTeam_teamId);
        System.out.println("getPatientsByTeam.result=" + _getPatientsByTeam__return);


        }
        {
        System.out.println("Invoking mpiLookup...");
        java.lang.String _mpiLookup_ssn = "";
        gov.va.medora.mdws.emrsvc.PatientArray _mpiLookup__return = port.mpiLookup(_mpiLookup_ssn);
        System.out.println("mpiLookup.result=" + _mpiLookup__return);


        }
        {
        System.out.println("Invoking getTeams...");
        gov.va.medora.mdws.emrsvc.TaggedText _getTeams__return = port.getTeams();
        System.out.println("getTeams.result=" + _getTeams__return);


        }
        {
        System.out.println("Invoking signNote...");
        java.lang.String _signNote_noteIEN = "";
        java.lang.String _signNote_userDUZ = "";
        java.lang.String _signNote_esig = "";
        gov.va.medora.mdws.emrsvc.TextTO _signNote__return = port.signNote(_signNote_noteIEN, _signNote_userDUZ, _signNote_esig);
        System.out.println("signNote.result=" + _signNote__return);


        }
        {
        System.out.println("Invoking getAdvanceDirectives...");
        java.lang.String _getAdvanceDirectives_fromDate = "";
        java.lang.String _getAdvanceDirectives_toDate = "";
        int _getAdvanceDirectives_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getAdvanceDirectives__return = port.getAdvanceDirectives(_getAdvanceDirectives_fromDate, _getAdvanceDirectives_toDate, _getAdvanceDirectives_nrpts);
        System.out.println("getAdvanceDirectives.result=" + _getAdvanceDirectives__return);


        }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_username = "";
        java.lang.String _login_pwd = "";
        java.lang.String _login_context = "";
        gov.va.medora.mdws.emrsvc.UserTO _login__return = port.login(_login_username, _login_pwd, _login_context);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking cprsLaunch...");
        java.lang.String _cprsLaunch_pwd = "";
        java.lang.String _cprsLaunch_sitecode = "";
        java.lang.String _cprsLaunch_duz = "";
        java.lang.String _cprsLaunch_dfn = "";
        gov.va.medora.mdws.emrsvc.PersonsTO _cprsLaunch__return = port.cprsLaunch(_cprsLaunch_pwd, _cprsLaunch_sitecode, _cprsLaunch_duz, _cprsLaunch_dfn);
        System.out.println("cprsLaunch.result=" + _cprsLaunch__return);


        }
        {
        System.out.println("Invoking getPatientsByProvider...");
        java.lang.String _getPatientsByProvider_duz = "";
        gov.va.medora.mdws.emrsvc.TaggedPatientArray _getPatientsByProvider__return = port.getPatientsByProvider(_getPatientsByProvider_duz);
        System.out.println("getPatientsByProvider.result=" + _getPatientsByProvider__return);


        }
        {
        System.out.println("Invoking getImagingReport...");
        java.lang.String _getImagingReport_ssn = "";
        java.lang.String _getImagingReport_accessionNumber = "";
        gov.va.medora.mdws.emrsvc.RadiologyReportTO _getImagingReport__return = port.getImagingReport(_getImagingReport_ssn, _getImagingReport_accessionNumber);
        System.out.println("getImagingReport.result=" + _getImagingReport__return);


        }
        {
        System.out.println("Invoking setVha...");
        java.lang.String _setVha_sitesFileName = "";
        gov.va.medora.mdws.emrsvc.SiteArray _setVha__return = port.setVha(_setVha_sitesFileName);
        System.out.println("setVha.result=" + _setVha__return);


        }
        {
        System.out.println("Invoking getSignedNotes...");
        java.lang.String _getSignedNotes_fromDate = "";
        java.lang.String _getSignedNotes_toDate = "";
        int _getSignedNotes_nNotes = 0;
        gov.va.medora.mdws.emrsvc.TaggedNoteArrays _getSignedNotes__return = port.getSignedNotes(_getSignedNotes_fromDate, _getSignedNotes_toDate, _getSignedNotes_nNotes);
        System.out.println("getSignedNotes.result=" + _getSignedNotes__return);


        }
        {
        System.out.println("Invoking getTransfersReports...");
        java.lang.String _getTransfersReports_fromDate = "";
        java.lang.String _getTransfersReports_toDate = "";
        int _getTransfersReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getTransfersReports__return = port.getTransfersReports(_getTransfersReports_fromDate, _getTransfersReports_toDate, _getTransfersReports_nrpts);
        System.out.println("getTransfersReports.result=" + _getTransfersReports__return);


        }
        {
        System.out.println("Invoking getAdmissionsReports...");
        java.lang.String _getAdmissionsReports_fromDate = "";
        java.lang.String _getAdmissionsReports_toDate = "";
        int _getAdmissionsReports_nrpts = 0;
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getAdmissionsReports__return = port.getAdmissionsReports(_getAdmissionsReports_fromDate, _getAdmissionsReports_toDate, _getAdmissionsReports_nrpts);
        System.out.println("getAdmissionsReports.result=" + _getAdmissionsReports__return);


        }
        {
        System.out.println("Invoking getOutpatientRxProfile...");
        gov.va.medora.mdws.emrsvc.TaggedTextArray _getOutpatientRxProfile__return = port.getOutpatientRxProfile();
        System.out.println("getOutpatientRxProfile.result=" + _getOutpatientRxProfile__return);


        }
        {
        System.out.println("Invoking getPatientsByClinic...");
        java.lang.String _getPatientsByClinic_clinicId = "";
        gov.va.medora.mdws.emrsvc.TaggedPatientArray _getPatientsByClinic__return = port.getPatientsByClinic(_getPatientsByClinic_clinicId);
        System.out.println("getPatientsByClinic.result=" + _getPatientsByClinic__return);


        }
        {
        System.out.println("Invoking getVISN...");
        java.lang.String _getVISN_regionId = "";
        gov.va.medora.mdws.emrsvc.RegionTO _getVISN__return = port.getVISN(_getVISN_regionId);
        System.out.println("getVISN.result=" + _getVISN__return);


        }

        System.exit(0);
    }

}
