package gov.va.medora.mdws.querysvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 05 13:14:31 MST 2011
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://mdws.medora.va.gov/QuerySvc", name = "QuerySvcSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface QuerySvcSoap {

    @WebResult(name = "matchResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "match", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.Match")
    @ResponseWrapper(localName = "matchResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.MatchResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/match")
    public gov.va.medora.mdws.querysvc.TaggedPatientArrays match(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String target
    );

    @WebResult(name = "selectResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "select", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.Select")
    @ResponseWrapper(localName = "selectResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.SelectResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/select")
    public gov.va.medora.mdws.querysvc.PatientTO select(
        @WebParam(name = "DFN", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String dfn
    );

    @WebResult(name = "loginResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "login", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.LoginResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/login")
    public gov.va.medora.mdws.querysvc.UserTO login(
        @WebParam(name = "username", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String username,
        @WebParam(name = "pwd", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String pwd,
        @WebParam(name = "context", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String context
    );

    @WebResult(name = "cprsUserLookupResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "cprsUserLookup", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.CprsUserLookup")
    @ResponseWrapper(localName = "cprsUserLookupResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.CprsUserLookupResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/cprsUserLookup")
    public gov.va.medora.mdws.querysvc.UserArray cprsUserLookup(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String target
    );

    @WebResult(name = "connectResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "connect", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.Connect")
    @ResponseWrapper(localName = "connectResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.ConnectResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/connect")
    public gov.va.medora.mdws.querysvc.DataSourceArray connect(
        @WebParam(name = "sitelist", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String sitelist
    );

    @WebResult(name = "getVHAResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "getVHA", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetVHA")
    @ResponseWrapper(localName = "getVHAResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetVHAResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/getVHA")
    public gov.va.medora.mdws.querysvc.RegionArray getVHA();

    @WebResult(name = "userLookupResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "userLookup", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.UserLookup")
    @ResponseWrapper(localName = "userLookupResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.UserLookupResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/userLookup")
    public gov.va.medora.mdws.querysvc.UserTO userLookup(
        @WebParam(name = "duz", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String duz
    );

    @WebResult(name = "getVariableValueResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "getVariableValue", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetVariableValue")
    @ResponseWrapper(localName = "getVariableValueResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetVariableValueResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/getVariableValue")
    public gov.va.medora.mdws.querysvc.TextTO getVariableValue(
        @WebParam(name = "arg", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String arg
    );

    @WebResult(name = "ddrListerResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "ddrLister", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.DdrLister")
    @ResponseWrapper(localName = "ddrListerResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.DdrListerResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/ddrLister")
    public gov.va.medora.mdws.querysvc.TextArray ddrLister(
        @WebParam(name = "file", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String file,
        @WebParam(name = "iens", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String iens,
        @WebParam(name = "fields", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String fields,
        @WebParam(name = "flags", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String flags,
        @WebParam(name = "maxrex", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String maxrex,
        @WebParam(name = "from", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String from,
        @WebParam(name = "part", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String part,
        @WebParam(name = "xref", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String xref,
        @WebParam(name = "screen", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String screen,
        @WebParam(name = "identifier", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String identifier
    );

    @WebResult(name = "setVhaResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "setVha", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.SetVha")
    @ResponseWrapper(localName = "setVhaResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.SetVhaResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/setVha")
    public gov.va.medora.mdws.querysvc.SiteArray setVha(
        @WebParam(name = "sitesFileName", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String sitesFileName
    );

    @WebResult(name = "getVersionResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetVersionResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/getVersion")
    public java.lang.String getVersion();

    @WebResult(name = "visitSiteResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "visitSite", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.VisitSite")
    @ResponseWrapper(localName = "visitSiteResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.VisitSiteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/visitSite")
    public gov.va.medora.mdws.querysvc.UserTO visitSite(
        @WebParam(name = "pwd", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String pwd,
        @WebParam(name = "sitecode", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String sitecode,
        @WebParam(name = "userSitecode", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String userSitecode,
        @WebParam(name = "userName", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String userName,
        @WebParam(name = "DUZ", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String duz,
        @WebParam(name = "SSN", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String ssn,
        @WebParam(name = "context", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String context
    );

    @WebResult(name = "siteHasPatchResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "siteHasPatch", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.SiteHasPatch")
    @ResponseWrapper(localName = "siteHasPatchResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.SiteHasPatchResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/siteHasPatch")
    public gov.va.medora.mdws.querysvc.TaggedText siteHasPatch(
        @WebParam(name = "patchId", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String patchId
    );

    @WebResult(name = "addDataSourceResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "addDataSource", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.AddDataSource")
    @ResponseWrapper(localName = "addDataSourceResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.AddDataSourceResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/addDataSource")
    public gov.va.medora.mdws.querysvc.SiteTO addDataSource(
        @WebParam(name = "id", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String name,
        @WebParam(name = "datasource", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String datasource,
        @WebParam(name = "port", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String port,
        @WebParam(name = "modality", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String modality,
        @WebParam(name = "protocol", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String protocol,
        @WebParam(name = "region", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String region
    );

    @WebResult(name = "disconnectResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "disconnect", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.Disconnect")
    @ResponseWrapper(localName = "disconnectResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.DisconnectResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/disconnect")
    public gov.va.medora.mdws.querysvc.TaggedTextArray disconnect();

    @WebResult(name = "ddrGetsEntryResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "ddrGetsEntry", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.DdrGetsEntry")
    @ResponseWrapper(localName = "ddrGetsEntryResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.DdrGetsEntryResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/ddrGetsEntry")
    public gov.va.medora.mdws.querysvc.TextArray ddrGetsEntry(
        @WebParam(name = "file", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String file,
        @WebParam(name = "iens", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String iens,
        @WebParam(name = "flds", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String flds,
        @WebParam(name = "flags", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String flags
    );

    @WebResult(name = "getFacadeVersionResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "getFacadeVersion", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetFacadeVersion")
    @ResponseWrapper(localName = "getFacadeVersionResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.GetFacadeVersionResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/getFacadeVersion")
    public gov.va.medora.mdws.querysvc.TextTO getFacadeVersion();

    @WebResult(name = "sitesHavePatchResult", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
    @RequestWrapper(localName = "sitesHavePatch", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.SitesHavePatch")
    @ResponseWrapper(localName = "sitesHavePatchResponse", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", className = "gov.va.medora.mdws.querysvc.SitesHavePatchResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/QuerySvc/sitesHavePatch")
    public gov.va.medora.mdws.querysvc.TaggedTextArray sitesHavePatch(
        @WebParam(name = "sitelist", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String sitelist,
        @WebParam(name = "patchId", targetNamespace = "http://mdws.medora.va.gov/QuerySvc")
        java.lang.String patchId
    );
}
