
/*
 * 
 */

package gov.va.medora.mdws.querysvc;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 05 13:14:31 MST 2011
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "QuerySvc", 
                  wsdlLocation = "file:src/main/resources/wsdl/querysvc.wsdl",
                  targetNamespace = "http://mdws.medora.va.gov/QuerySvc") 
public class QuerySvc extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://mdws.medora.va.gov/QuerySvc", "QuerySvc");
    public final static QName QuerySvcHttpGet = new QName("http://mdws.medora.va.gov/QuerySvc", "QuerySvcHttpGet");
    public final static QName QuerySvcHttpPost = new QName("http://mdws.medora.va.gov/QuerySvc", "QuerySvcHttpPost");
    public final static QName QuerySvcSoap = new QName("http://mdws.medora.va.gov/QuerySvc", "QuerySvcSoap");
    public final static QName QuerySvcSoap12 = new QName("http://mdws.medora.va.gov/QuerySvc", "QuerySvcSoap12");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/wsdl/querysvc.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:src/main/resources/wsdl/querysvc.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public QuerySvc(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public QuerySvc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuerySvc() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns QuerySvcHttpGet
     */
    @WebEndpoint(name = "QuerySvcHttpGet")
    public QuerySvcHttpGet getQuerySvcHttpGet() {
        return super.getPort(QuerySvcHttpGet, QuerySvcHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySvcHttpGet
     */
    @WebEndpoint(name = "QuerySvcHttpGet")
    public QuerySvcHttpGet getQuerySvcHttpGet(WebServiceFeature... features) {
        return super.getPort(QuerySvcHttpGet, QuerySvcHttpGet.class, features);
    }
    /**
     * 
     * @return
     *     returns QuerySvcHttpPost
     */
    @WebEndpoint(name = "QuerySvcHttpPost")
    public QuerySvcHttpPost getQuerySvcHttpPost() {
        return super.getPort(QuerySvcHttpPost, QuerySvcHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySvcHttpPost
     */
    @WebEndpoint(name = "QuerySvcHttpPost")
    public QuerySvcHttpPost getQuerySvcHttpPost(WebServiceFeature... features) {
        return super.getPort(QuerySvcHttpPost, QuerySvcHttpPost.class, features);
    }
    /**
     * 
     * @return
     *     returns QuerySvcSoap
     */
    @WebEndpoint(name = "QuerySvcSoap")
    public QuerySvcSoap getQuerySvcSoap() {
        return super.getPort(QuerySvcSoap, QuerySvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySvcSoap
     */
    @WebEndpoint(name = "QuerySvcSoap")
    public QuerySvcSoap getQuerySvcSoap(WebServiceFeature... features) {
        return super.getPort(QuerySvcSoap, QuerySvcSoap.class, features);
    }
    /**
     * 
     * @return
     *     returns QuerySvcSoap
     */
    @WebEndpoint(name = "QuerySvcSoap12")
    public QuerySvcSoap getQuerySvcSoap12() {
        return super.getPort(QuerySvcSoap12, QuerySvcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySvcSoap
     */
    @WebEndpoint(name = "QuerySvcSoap12")
    public QuerySvcSoap getQuerySvcSoap12(WebServiceFeature... features) {
        return super.getPort(QuerySvcSoap12, QuerySvcSoap.class, features);
    }

}
