package gov.va.medora.mdws.emrsvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 05 13:15:55 MST 2011
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://mdws.medora.va.gov/EmrSvc", name = "EmrSvcSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface EmrSvcSoap {

    @WebResult(name = "getWardsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getWards", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetWards")
    @ResponseWrapper(localName = "getWardsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetWardsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getWards")
    public gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray getWards();

    @WebResult(name = "getRadiologyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getRadiologyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetRadiologyReports")
    @ResponseWrapper(localName = "getRadiologyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetRadiologyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getRadiologyReports")
    public gov.va.medora.mdws.emrsvc.TaggedRadiologyReportArrays getRadiologyReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getCytologyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getCytologyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCytologyReports")
    @ResponseWrapper(localName = "getCytologyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCytologyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getCytologyReports")
    public gov.va.medora.mdws.emrsvc.TaggedCytologyRptArrays getCytologyReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getVisitsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getVisits", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVisits")
    @ResponseWrapper(localName = "getVisitsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVisitsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getVisits")
    public gov.va.medora.mdws.emrsvc.TaggedVisitArray getVisits(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate
    );

    @WebResult(name = "getCrisisNotesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getCrisisNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCrisisNotes")
    @ResponseWrapper(localName = "getCrisisNotesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCrisisNotesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getCrisisNotes")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getCrisisNotes(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getSurgeryReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getSurgeryReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgeryReports")
    @ResponseWrapper(localName = "getSurgeryReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgeryReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getSurgeryReports")
    public gov.va.medora.mdws.emrsvc.TaggedSurgeryReportArrays getSurgeryReports();

    @WebResult(name = "getIvMedsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getIvMeds", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetIvMeds")
    @ResponseWrapper(localName = "getIvMedsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetIvMedsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getIvMeds")
    public gov.va.medora.mdws.emrsvc.TaggedMedicationArrays getIvMeds();

    @WebResult(name = "getAllOrdersResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAllOrders", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAllOrders")
    @ResponseWrapper(localName = "getAllOrdersResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAllOrdersResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAllOrders")
    public gov.va.medora.mdws.emrsvc.TaggedOrderArrays getAllOrders();

    @WebResult(name = "getConfidentialityResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getConfidentiality", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetConfidentiality")
    @ResponseWrapper(localName = "getConfidentialityResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetConfidentialityResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getConfidentiality")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getConfidentiality();

    @WebResult(name = "getSurgeryReportsWithTextResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getSurgeryReportsWithText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgeryReportsWithText")
    @ResponseWrapper(localName = "getSurgeryReportsWithTextResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgeryReportsWithTextResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getSurgeryReportsWithText")
    public gov.va.medora.mdws.emrsvc.TaggedSurgeryReportArrays getSurgeryReportsWithText();

    @WebResult(name = "getVitalSignsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getVitalSigns", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVitalSigns")
    @ResponseWrapper(localName = "getVitalSignsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVitalSignsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getVitalSigns")
    public gov.va.medora.mdws.emrsvc.TaggedVitalSignSetArrays getVitalSigns();

    @WebResult(name = "getChemHemReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getChemHemReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetChemHemReports")
    @ResponseWrapper(localName = "getChemHemReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetChemHemReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getChemHemReports")
    public gov.va.medora.mdws.emrsvc.TaggedChemHemRptArrays getChemHemReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getMedsAdminHxResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getMedsAdminHx", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMedsAdminHx")
    @ResponseWrapper(localName = "getMedsAdminHxResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMedsAdminHxResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getMedsAdminHx")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getMedsAdminHx(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getImmunizationsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getImmunizations", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetImmunizations")
    @ResponseWrapper(localName = "getImmunizationsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetImmunizationsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getImmunizations")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getImmunizations(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "closeNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "closeNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.CloseNote")
    @ResponseWrapper(localName = "closeNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.CloseNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/closeNote")
    public gov.va.medora.mdws.emrsvc.TextTO closeNote(
        @WebParam(name = "noteIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteIEN,
        @WebParam(name = "consultIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String consultIEN
    );

    @WebResult(name = "selectResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "select", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.Select")
    @ResponseWrapper(localName = "selectResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.SelectResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/select")
    public gov.va.medora.mdws.emrsvc.PatientTO select(
        @WebParam(name = "DFN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String dfn
    );

    @WebResult(name = "getProblemListResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getProblemList", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetProblemList")
    @ResponseWrapper(localName = "getProblemListResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetProblemListResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getProblemList")
    public gov.va.medora.mdws.emrsvc.TaggedProblemArrays getProblemList(
        @WebParam(name = "type", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String type
    );

    @WebResult(name = "getSurgicalPathologyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getSurgicalPathologyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgicalPathologyReports")
    @ResponseWrapper(localName = "getSurgicalPathologyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgicalPathologyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getSurgicalPathologyReports")
    public gov.va.medora.mdws.emrsvc.TaggedSurgicalPathologyRptArrays getSurgicalPathologyReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getMicrobiologyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getMicrobiologyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMicrobiologyReports")
    @ResponseWrapper(localName = "getMicrobiologyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMicrobiologyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getMicrobiologyReports")
    public gov.va.medora.mdws.emrsvc.TaggedMicrobiologyRptArrays getMicrobiologyReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getExpandedAdtReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getExpandedAdtReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetExpandedAdtReports")
    @ResponseWrapper(localName = "getExpandedAdtReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetExpandedAdtReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getExpandedAdtReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getExpandedAdtReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getIcdProceduresReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getIcdProceduresReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetIcdProceduresReports")
    @ResponseWrapper(localName = "getIcdProceduresReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetIcdProceduresReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getIcdProceduresReports")
    public gov.va.medora.mdws.emrsvc.TaggedIcdRptArrays getIcdProceduresReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getAllMedsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAllMeds", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAllMeds")
    @ResponseWrapper(localName = "getAllMedsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAllMedsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAllMeds")
    public gov.va.medora.mdws.emrsvc.TaggedMedicationArrays getAllMeds();

    @WebResult(name = "cprsUserLookupResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "cprsUserLookup", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.CprsUserLookup")
    @ResponseWrapper(localName = "cprsUserLookupResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.CprsUserLookupResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/cprsUserLookup")
    public gov.va.medora.mdws.emrsvc.UserArray cprsUserLookup(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String target
    );

    @WebResult(name = "getMedsAdminLogResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getMedsAdminLog", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMedsAdminLog")
    @ResponseWrapper(localName = "getMedsAdminLogResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMedsAdminLogResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getMedsAdminLog")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getMedsAdminLog(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "visitResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "visit", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.Visit")
    @ResponseWrapper(localName = "visitResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.VisitResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/visit")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray visit(
        @WebParam(name = "pwd", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String pwd,
        @WebParam(name = "sitelist", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String sitelist,
        @WebParam(name = "userSitecode", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String userSitecode,
        @WebParam(name = "userName", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String userName,
        @WebParam(name = "DUZ", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String duz,
        @WebParam(name = "SSN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String ssn,
        @WebParam(name = "context", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String context
    );

    @WebResult(name = "getTreatingSpecialtyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getTreatingSpecialtyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetTreatingSpecialtyReports")
    @ResponseWrapper(localName = "getTreatingSpecialtyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetTreatingSpecialtyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getTreatingSpecialtyReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getTreatingSpecialtyReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "setupMultiSiteQueryResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "setupMultiSiteQuery", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.SetupMultiSiteQuery")
    @ResponseWrapper(localName = "setupMultiSiteQueryResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.SetupMultiSiteQueryResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/setupMultiSiteQuery")
    public gov.va.medora.mdws.emrsvc.SiteArray setupMultiSiteQuery(
        @WebParam(name = "appPwd", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String appPwd
    );

    @WebResult(name = "getLocationsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getLocations", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetLocations")
    @ResponseWrapper(localName = "getLocationsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetLocationsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getLocations")
    public gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray getLocations(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String target,
        @WebParam(name = "direction", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String direction
    );

    @WebResult(name = "getFutureClinicVisitsReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getFutureClinicVisitsReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetFutureClinicVisitsReports")
    @ResponseWrapper(localName = "getFutureClinicVisitsReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetFutureClinicVisitsReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getFutureClinicVisitsReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getFutureClinicVisitsReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "isOneVisitNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "isOneVisitNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsOneVisitNote")
    @ResponseWrapper(localName = "isOneVisitNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsOneVisitNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/isOneVisitNote")
    public gov.va.medora.mdws.emrsvc.TaggedText isOneVisitNote(
        @WebParam(name = "noteDefinitionIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteDefinitionIEN,
        @WebParam(name = "noteTitle", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteTitle,
        @WebParam(name = "visitString", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String visitString
    );

    @WebResult(name = "isCosignerRequiredResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "isCosignerRequired", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsCosignerRequired")
    @ResponseWrapper(localName = "isCosignerRequiredResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsCosignerRequiredResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/isCosignerRequired")
    public gov.va.medora.mdws.emrsvc.TextTO isCosignerRequired(
        @WebParam(name = "noteDefinitionIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteDefinitionIEN,
        @WebParam(name = "authorDUZ", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String authorDUZ
    );

    @WebResult(name = "getCytopathologyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getCytopathologyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCytopathologyReports")
    @ResponseWrapper(localName = "getCytopathologyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCytopathologyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getCytopathologyReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getCytopathologyReports();

    @WebResult(name = "getSurgeryReportTextResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getSurgeryReportText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgeryReportText")
    @ResponseWrapper(localName = "getSurgeryReportTextResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSurgeryReportTextResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getSurgeryReportText")
    public gov.va.medora.mdws.emrsvc.TextTO getSurgeryReportText(
        @WebParam(name = "siteId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String siteId,
        @WebParam(name = "rptId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String rptId
    );

    @WebResult(name = "getElectronMicroscopyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getElectronMicroscopyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetElectronMicroscopyReports")
    @ResponseWrapper(localName = "getElectronMicroscopyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetElectronMicroscopyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getElectronMicroscopyReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getElectronMicroscopyReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "isValidEsigResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "isValidEsig", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsValidEsig")
    @ResponseWrapper(localName = "isValidEsigResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsValidEsigResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/isValidEsig")
    public gov.va.medora.mdws.emrsvc.TextTO isValidEsig(
        @WebParam(name = "esig", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String esig
    );

    @WebResult(name = "issueConfidentialityBulletinResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "issueConfidentialityBulletin", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IssueConfidentialityBulletin")
    @ResponseWrapper(localName = "issueConfidentialityBulletinResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IssueConfidentialityBulletinResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/issueConfidentialityBulletin")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray issueConfidentialityBulletin();

    @WebResult(name = "getDischargesReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getDischargesReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDischargesReports")
    @ResponseWrapper(localName = "getDischargesReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDischargesReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getDischargesReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getDischargesReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getMedicationDetailResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getMedicationDetail", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMedicationDetail")
    @ResponseWrapper(localName = "getMedicationDetailResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetMedicationDetailResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getMedicationDetail")
    public gov.va.medora.mdws.emrsvc.TextTO getMedicationDetail(
        @WebParam(name = "siteId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String siteId,
        @WebParam(name = "medId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String medId
    );

    @WebResult(name = "getOutpatientEncounterReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getOutpatientEncounterReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOutpatientEncounterReports")
    @ResponseWrapper(localName = "getOutpatientEncounterReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOutpatientEncounterReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getOutpatientEncounterReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getOutpatientEncounterReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getBloodTransfusionReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getBloodTransfusionReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetBloodTransfusionReports")
    @ResponseWrapper(localName = "getBloodTransfusionReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetBloodTransfusionReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getBloodTransfusionReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getBloodTransfusionReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getClinicsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getClinics", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetClinics")
    @ResponseWrapper(localName = "getClinicsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetClinicsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getClinics")
    public gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray getClinics(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String target
    );

    @WebResult(name = "getPatientsByWardResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getPatientsByWard", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByWard")
    @ResponseWrapper(localName = "getPatientsByWardResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByWardResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getPatientsByWard")
    public gov.va.medora.mdws.emrsvc.TaggedPatientArray getPatientsByWard(
        @WebParam(name = "wardId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String wardId
    );

    @WebResult(name = "nptLookupResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "nptLookup", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.NptLookup")
    @ResponseWrapper(localName = "nptLookupResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.NptLookupResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/nptLookup")
    public gov.va.medora.mdws.emrsvc.PatientArray nptLookup(
        @WebParam(name = "SSN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String ssn
    );

    @WebResult(name = "getDischargeSummariesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getDischargeSummaries", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDischargeSummaries")
    @ResponseWrapper(localName = "getDischargeSummariesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDischargeSummariesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getDischargeSummaries")
    public gov.va.medora.mdws.emrsvc.TaggedNoteArrays getDischargeSummaries(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nNotes
    );

    @WebResult(name = "getVHAResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getVHA", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVHA")
    @ResponseWrapper(localName = "getVHAResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVHAResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getVHA")
    public gov.va.medora.mdws.emrsvc.RegionArray getVHA();

    @WebResult(name = "getPrfNoteActionsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getPrfNoteActions", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPrfNoteActions")
    @ResponseWrapper(localName = "getPrfNoteActionsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPrfNoteActionsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getPrfNoteActions")
    public gov.va.medora.mdws.emrsvc.PatientRecordFlagArray getPrfNoteActions(
        @WebParam(name = "noteDefinitionIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "getPastClinicVisitsReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getPastClinicVisitsReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPastClinicVisitsReports")
    @ResponseWrapper(localName = "getPastClinicVisitsReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPastClinicVisitsReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getPastClinicVisitsReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getPastClinicVisitsReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "isSurgeryNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "isSurgeryNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsSurgeryNote")
    @ResponseWrapper(localName = "isSurgeryNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsSurgeryNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/isSurgeryNote")
    public gov.va.medora.mdws.emrsvc.TaggedText isSurgeryNote(
        @WebParam(name = "noteDefinitionIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "patientInquiryResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "patientInquiry", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.PatientInquiry")
    @ResponseWrapper(localName = "patientInquiryResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.PatientInquiryResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/patientInquiry")
    public gov.va.medora.mdws.emrsvc.TextTO patientInquiry();

    @WebResult(name = "getOtherMedsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getOtherMeds", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOtherMeds")
    @ResponseWrapper(localName = "getOtherMedsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOtherMedsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getOtherMeds")
    public gov.va.medora.mdws.emrsvc.TaggedMedicationArrays getOtherMeds();

    @WebResult(name = "getBloodBankReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getBloodBankReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetBloodBankReports")
    @ResponseWrapper(localName = "getBloodBankReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetBloodBankReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getBloodBankReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getBloodBankReports();

    @WebResult(name = "getFacadeVersionResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getFacadeVersion", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetFacadeVersion")
    @ResponseWrapper(localName = "getFacadeVersionResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetFacadeVersionResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getFacadeVersion")
    public gov.va.medora.mdws.emrsvc.TextTO getFacadeVersion();

    @WebResult(name = "getAllergiesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAllergies", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAllergies")
    @ResponseWrapper(localName = "getAllergiesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAllergiesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAllergies")
    public gov.va.medora.mdws.emrsvc.TaggedAllergyArrays getAllergies();

    @WebResult(name = "getVersionResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getVersion", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVersion")
    @ResponseWrapper(localName = "getVersionResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVersionResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getVersion")
    public java.lang.String getVersion();

    @WebResult(name = "getNoteTitlesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getNoteTitles", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetNoteTitles")
    @ResponseWrapper(localName = "getNoteTitlesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetNoteTitlesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getNoteTitles")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getNoteTitles(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String target,
        @WebParam(name = "direction", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String direction
    );

    @WebResult(name = "getAppointmentTextResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAppointmentText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAppointmentText")
    @ResponseWrapper(localName = "getAppointmentTextResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAppointmentTextResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAppointmentText")
    public gov.va.medora.mdws.emrsvc.TextTO getAppointmentText(
        @WebParam(name = "siteId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String siteId,
        @WebParam(name = "apptId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String apptId
    );

    @WebResult(name = "getSpecialtiesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getSpecialties", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSpecialties")
    @ResponseWrapper(localName = "getSpecialtiesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSpecialtiesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getSpecialties")
    public gov.va.medora.mdws.emrsvc.TaggedText getSpecialties();

    @WebResult(name = "writeSimpleOrderByPolicyResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "writeSimpleOrderByPolicy", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.WriteSimpleOrderByPolicy")
    @ResponseWrapper(localName = "writeSimpleOrderByPolicyResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.WriteSimpleOrderByPolicyResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/writeSimpleOrderByPolicy")
    public gov.va.medora.mdws.emrsvc.OrderTO writeSimpleOrderByPolicy(
        @WebParam(name = "providerDUZ", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String providerDUZ,
        @WebParam(name = "esig", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String esig,
        @WebParam(name = "locationIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String locationIEN,
        @WebParam(name = "orderIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String orderIEN,
        @WebParam(name = "startDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String startDate
    );

    @WebResult(name = "getConsultsForPatientResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getConsultsForPatient", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetConsultsForPatient")
    @ResponseWrapper(localName = "getConsultsForPatientResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetConsultsForPatientResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getConsultsForPatient")
    public gov.va.medora.mdws.emrsvc.TaggedConsultArrays getConsultsForPatient();

    @WebResult(name = "writeNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "writeNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.WriteNote")
    @ResponseWrapper(localName = "writeNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.WriteNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/writeNote")
    public gov.va.medora.mdws.emrsvc.NoteResultTO writeNote(
        @WebParam(name = "titleIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String titleIEN,
        @WebParam(name = "encounterString", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String encounterString,
        @WebParam(name = "text", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String text,
        @WebParam(name = "authorDUZ", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String authorDUZ,
        @WebParam(name = "cosignerDUZ", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String cosignerDUZ,
        @WebParam(name = "consultIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String consultIEN,
        @WebParam(name = "prfIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String prfIEN
    );

    @WebResult(name = "getNotesWithTextResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getNotesWithText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetNotesWithText")
    @ResponseWrapper(localName = "getNotesWithTextResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetNotesWithTextResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getNotesWithText")
    public gov.va.medora.mdws.emrsvc.TaggedNoteArrays getNotesWithText(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nNotes
    );

    @WebResult(name = "getBloodAvailabilityReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getBloodAvailabilityReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetBloodAvailabilityReports")
    @ResponseWrapper(localName = "getBloodAvailabilityReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetBloodAvailabilityReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getBloodAvailabilityReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getBloodAvailabilityReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "isPrfNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "isPrfNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsPrfNote")
    @ResponseWrapper(localName = "isPrfNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsPrfNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/isPrfNote")
    public gov.va.medora.mdws.emrsvc.TextTO isPrfNote(
        @WebParam(name = "noteDefinitionIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "addDataSourceResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "addDataSource", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.AddDataSource")
    @ResponseWrapper(localName = "addDataSourceResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.AddDataSourceResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/addDataSource")
    public gov.va.medora.mdws.emrsvc.SiteTO addDataSource(
        @WebParam(name = "id", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String id,
        @WebParam(name = "name", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String name,
        @WebParam(name = "datasource", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String datasource,
        @WebParam(name = "port", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String port,
        @WebParam(name = "modality", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String modality,
        @WebParam(name = "protocol", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String protocol,
        @WebParam(name = "region", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String region
    );

    @WebResult(name = "getCareTeamReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getCareTeamReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCareTeamReports")
    @ResponseWrapper(localName = "getCareTeamReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCareTeamReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getCareTeamReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getCareTeamReports();

    @WebResult(name = "getImoMedsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getImoMeds", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetImoMeds")
    @ResponseWrapper(localName = "getImoMedsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetImoMedsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getImoMeds")
    public gov.va.medora.mdws.emrsvc.TaggedMedicationArrays getImoMeds();

    @WebResult(name = "getIcdSurgeryReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getIcdSurgeryReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetIcdSurgeryReports")
    @ResponseWrapper(localName = "getIcdSurgeryReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetIcdSurgeryReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getIcdSurgeryReports")
    public gov.va.medora.mdws.emrsvc.TaggedIcdRptArrays getIcdSurgeryReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getDischargeDiagnosisReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getDischargeDiagnosisReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDischargeDiagnosisReports")
    @ResponseWrapper(localName = "getDischargeDiagnosisReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDischargeDiagnosisReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getDischargeDiagnosisReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getDischargeDiagnosisReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "connectResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "connect", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.Connect")
    @ResponseWrapper(localName = "connectResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.ConnectResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/connect")
    public gov.va.medora.mdws.emrsvc.DataSourceArray connect(
        @WebParam(name = "sitelist", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String sitelist
    );

    @WebResult(name = "getAutopsyReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAutopsyReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAutopsyReports")
    @ResponseWrapper(localName = "getAutopsyReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAutopsyReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAutopsyReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getAutopsyReports();

    @WebResult(name = "getUnsignedNotesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getUnsignedNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetUnsignedNotes")
    @ResponseWrapper(localName = "getUnsignedNotesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetUnsignedNotesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getUnsignedNotes")
    public gov.va.medora.mdws.emrsvc.TaggedNoteArrays getUnsignedNotes(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nNotes
    );

    @WebResult(name = "getAppointmentsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAppointments", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAppointments")
    @ResponseWrapper(localName = "getAppointmentsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAppointmentsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAppointments")
    public gov.va.medora.mdws.emrsvc.TaggedAppointmentArrays getAppointments();

    @WebResult(name = "getUnitDoseMedsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getUnitDoseMeds", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetUnitDoseMeds")
    @ResponseWrapper(localName = "getUnitDoseMedsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetUnitDoseMedsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getUnitDoseMeds")
    public gov.va.medora.mdws.emrsvc.TaggedMedicationArrays getUnitDoseMeds();

    @WebResult(name = "getAdmissionsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAdmissions", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAdmissions")
    @ResponseWrapper(localName = "getAdmissionsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAdmissionsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAdmissions")
    public gov.va.medora.mdws.emrsvc.TaggedInpatientStayArray getAdmissions();

    @WebResult(name = "getPatientsBySpecialtyResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getPatientsBySpecialty", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsBySpecialty")
    @ResponseWrapper(localName = "getPatientsBySpecialtyResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsBySpecialtyResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getPatientsBySpecialty")
    public gov.va.medora.mdws.emrsvc.TaggedPatientArray getPatientsBySpecialty(
        @WebParam(name = "specialtyId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String specialtyId
    );

    @WebResult(name = "getDemographicsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getDemographics", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDemographics")
    @ResponseWrapper(localName = "getDemographicsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetDemographicsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getDemographics")
    public gov.va.medora.mdws.emrsvc.PatientTO getDemographics();

    @WebResult(name = "getHospitalLocationsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getHospitalLocations", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetHospitalLocations")
    @ResponseWrapper(localName = "getHospitalLocationsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetHospitalLocationsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getHospitalLocations")
    public gov.va.medora.mdws.emrsvc.TaggedHospitalLocationArray getHospitalLocations(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String target,
        @WebParam(name = "direction", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String direction
    );

    @WebResult(name = "getCompAndPenReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getCompAndPenReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCompAndPenReports")
    @ResponseWrapper(localName = "getCompAndPenReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetCompAndPenReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getCompAndPenReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getCompAndPenReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetNote")
    @ResponseWrapper(localName = "getNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getNote")
    public gov.va.medora.mdws.emrsvc.TextTO getNote(
        @WebParam(name = "siteId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String siteId,
        @WebParam(name = "noteId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteId
    );

    @WebResult(name = "getLatestVitalSignsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getLatestVitalSigns", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetLatestVitalSigns")
    @ResponseWrapper(localName = "getLatestVitalSignsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetLatestVitalSignsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getLatestVitalSigns")
    public gov.va.medora.mdws.emrsvc.TaggedVitalSignArrays getLatestVitalSigns();

    @WebResult(name = "matchResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "match", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.Match")
    @ResponseWrapper(localName = "matchResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.MatchResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/match")
    public gov.va.medora.mdws.emrsvc.TaggedPatientArrays match(
        @WebParam(name = "target", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String target
    );

    @WebResult(name = "isConsultNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "isConsultNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsConsultNote")
    @ResponseWrapper(localName = "isConsultNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.IsConsultNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/isConsultNote")
    public gov.va.medora.mdws.emrsvc.TextTO isConsultNote(
        @WebParam(name = "noteDefinitionIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "disconnectRemoteSitesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "disconnectRemoteSites", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.DisconnectRemoteSites")
    @ResponseWrapper(localName = "disconnectRemoteSitesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.DisconnectRemoteSitesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/disconnectRemoteSites")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray disconnectRemoteSites();

    @WebResult(name = "getClinicalWarningsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getClinicalWarnings", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetClinicalWarnings")
    @ResponseWrapper(localName = "getClinicalWarningsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetClinicalWarningsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getClinicalWarnings")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getClinicalWarnings(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "disconnectResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "disconnect", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.Disconnect")
    @ResponseWrapper(localName = "disconnectResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.DisconnectResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/disconnect")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray disconnect();

    @WebResult(name = "getUncosignedNotesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getUncosignedNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetUncosignedNotes")
    @ResponseWrapper(localName = "getUncosignedNotesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetUncosignedNotesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getUncosignedNotes")
    public gov.va.medora.mdws.emrsvc.TaggedNoteArrays getUncosignedNotes(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nNotes
    );

    @WebResult(name = "getOutpatientMedsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getOutpatientMeds", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOutpatientMeds")
    @ResponseWrapper(localName = "getOutpatientMedsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOutpatientMedsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getOutpatientMeds")
    public gov.va.medora.mdws.emrsvc.TaggedMedicationArrays getOutpatientMeds();

    @WebResult(name = "getPatientsByTeamResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getPatientsByTeam", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByTeam")
    @ResponseWrapper(localName = "getPatientsByTeamResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByTeamResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getPatientsByTeam")
    public gov.va.medora.mdws.emrsvc.TaggedPatientArray getPatientsByTeam(
        @WebParam(name = "teamId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String teamId
    );

    @WebResult(name = "mpiLookupResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "mpiLookup", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.MpiLookup")
    @ResponseWrapper(localName = "mpiLookupResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.MpiLookupResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/mpiLookup")
    public gov.va.medora.mdws.emrsvc.PatientArray mpiLookup(
        @WebParam(name = "SSN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String ssn
    );

    @WebResult(name = "getTeamsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getTeams", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetTeams")
    @ResponseWrapper(localName = "getTeamsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetTeamsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getTeams")
    public gov.va.medora.mdws.emrsvc.TaggedText getTeams();

    @WebResult(name = "signNoteResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "signNote", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.SignNote")
    @ResponseWrapper(localName = "signNoteResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.SignNoteResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/signNote")
    public gov.va.medora.mdws.emrsvc.TextTO signNote(
        @WebParam(name = "noteIEN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String noteIEN,
        @WebParam(name = "userDUZ", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String userDUZ,
        @WebParam(name = "esig", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String esig
    );

    @WebResult(name = "getAdvanceDirectivesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAdvanceDirectives", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAdvanceDirectives")
    @ResponseWrapper(localName = "getAdvanceDirectivesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAdvanceDirectivesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAdvanceDirectives")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getAdvanceDirectives(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "loginResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "login", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.LoginResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/login")
    public gov.va.medora.mdws.emrsvc.UserTO login(
        @WebParam(name = "username", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String username,
        @WebParam(name = "pwd", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String pwd,
        @WebParam(name = "context", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String context
    );

    @WebResult(name = "cprsLaunchResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "cprsLaunch", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.CprsLaunch")
    @ResponseWrapper(localName = "cprsLaunchResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.CprsLaunchResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/cprsLaunch")
    public gov.va.medora.mdws.emrsvc.PersonsTO cprsLaunch(
        @WebParam(name = "pwd", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String pwd,
        @WebParam(name = "sitecode", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String sitecode,
        @WebParam(name = "DUZ", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String duz,
        @WebParam(name = "DFN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String dfn
    );

    @WebResult(name = "getPatientsByProviderResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getPatientsByProvider", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByProvider")
    @ResponseWrapper(localName = "getPatientsByProviderResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByProviderResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getPatientsByProvider")
    public gov.va.medora.mdws.emrsvc.TaggedPatientArray getPatientsByProvider(
        @WebParam(name = "duz", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String duz
    );

    @WebResult(name = "getImagingReportResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getImagingReport", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetImagingReport")
    @ResponseWrapper(localName = "getImagingReportResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetImagingReportResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getImagingReport")
    public gov.va.medora.mdws.emrsvc.RadiologyReportTO getImagingReport(
        @WebParam(name = "SSN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String ssn,
        @WebParam(name = "accessionNumber", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String accessionNumber
    );

    @WebResult(name = "setVhaResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "setVha", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.SetVha")
    @ResponseWrapper(localName = "setVhaResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.SetVhaResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/setVha")
    public gov.va.medora.mdws.emrsvc.SiteArray setVha(
        @WebParam(name = "sitesFileName", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String sitesFileName
    );

    @WebResult(name = "getSignedNotesResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getSignedNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSignedNotes")
    @ResponseWrapper(localName = "getSignedNotesResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetSignedNotesResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getSignedNotes")
    public gov.va.medora.mdws.emrsvc.TaggedNoteArrays getSignedNotes(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nNotes", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nNotes
    );

    @WebResult(name = "getTransfersReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getTransfersReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetTransfersReports")
    @ResponseWrapper(localName = "getTransfersReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetTransfersReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getTransfersReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getTransfersReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getAdmissionsReportsResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getAdmissionsReports", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAdmissionsReports")
    @ResponseWrapper(localName = "getAdmissionsReportsResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetAdmissionsReportsResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getAdmissionsReports")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getAdmissionsReports(
        @WebParam(name = "fromDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String fromDate,
        @WebParam(name = "toDate", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String toDate,
        @WebParam(name = "nrpts", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        int nrpts
    );

    @WebResult(name = "getOutpatientRxProfileResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getOutpatientRxProfile", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOutpatientRxProfile")
    @ResponseWrapper(localName = "getOutpatientRxProfileResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetOutpatientRxProfileResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getOutpatientRxProfile")
    public gov.va.medora.mdws.emrsvc.TaggedTextArray getOutpatientRxProfile();

    @WebResult(name = "getPatientsByClinicResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getPatientsByClinic", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByClinic")
    @ResponseWrapper(localName = "getPatientsByClinicResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetPatientsByClinicResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getPatientsByClinic")
    public gov.va.medora.mdws.emrsvc.TaggedPatientArray getPatientsByClinic(
        @WebParam(name = "clinicId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String clinicId
    );

    @WebResult(name = "getVISNResult", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
    @RequestWrapper(localName = "getVISN", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVISN")
    @ResponseWrapper(localName = "getVISNResponse", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", className = "gov.va.medora.mdws.emrsvc.GetVISNResponse")
    @WebMethod(action = "http://mdws.medora.va.gov/EmrSvc/getVISN")
    public gov.va.medora.mdws.emrsvc.RegionTO getVISN(
        @WebParam(name = "regionId", targetNamespace = "http://mdws.medora.va.gov/EmrSvc")
        java.lang.String regionId
    );
}
