package gov.med.va.innovations.domain;

import java.util.Date;

public class EventType {
	private Integer eventTypeId;
	private String code;
	private String description;
	private String status;
	private String createdBy;
	private String updatedBy;
	private Date updateDate;
	private byte[] createDate;

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.event_type_id
	 * @return  the value of dbo.event_type.event_type_id
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public Integer getEventTypeId() {
		return eventTypeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.event_type_id
	 * @param eventTypeId  the value for dbo.event_type.event_type_id
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setEventTypeId(Integer eventTypeId) {
		this.eventTypeId = eventTypeId;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.code
	 * @return  the value of dbo.event_type.code
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.code
	 * @param code  the value for dbo.event_type.code
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.description
	 * @return  the value of dbo.event_type.description
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.description
	 * @param description  the value for dbo.event_type.description
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.status
	 * @return  the value of dbo.event_type.status
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.status
	 * @param status  the value for dbo.event_type.status
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.created_by
	 * @return  the value of dbo.event_type.created_by
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public String getCreatedBy() {
		return createdBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.created_by
	 * @param createdBy  the value for dbo.event_type.created_by
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.updated_by
	 * @return  the value of dbo.event_type.updated_by
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public String getUpdatedBy() {
		return updatedBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.updated_by
	 * @param updatedBy  the value for dbo.event_type.updated_by
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.update_date
	 * @return  the value of dbo.event_type.update_date
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public Date getUpdateDate() {
		return updateDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.update_date
	 * @param updateDate  the value for dbo.event_type.update_date
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column dbo.event_type.create_date
	 * @return  the value of dbo.event_type.create_date
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public byte[] getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column dbo.event_type.create_date
	 * @param createDate  the value for dbo.event_type.create_date
	 * @ibatorgenerated  Fri May 21 20:55:48 MDT 2010
	 */
	public void setCreateDate(byte[] createDate) {
		this.createDate = createDate;
	}
}