package gov.med.va.innovations.domain;

import java.util.Date;

public class DocumentEvent {
    private Long documentEventId;
    private EventType eventType = new EventType();
    private Date eventDate;
    private String documentId;
    private String patientId;
    private String firstName;
    private String lastName;
    private String ssn;
    private String dob;
    private Integer medUnitId;    
    private String updatedBy;
    private Date updateTime;
    private String eventTargetId;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.document_event_id
     *
     * @return the value of dbo.document_event.document_event_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public Long getDocumentEventId() {
        return documentEventId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.document_event_id
     *
     * @param documentEventId the value for dbo.document_event.document_event_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setDocumentEventId(Long documentEventId) {
        this.documentEventId = documentEventId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.event_type_id
     *
     * @return the value of dbo.document_event.event_type_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public EventType getEventType() {
        return eventType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.event_type_id
     *
     * @param eventTypeId the value for dbo.document_event.event_type_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setEventType(EventType eventType) {
        this.eventType = eventType;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.event_date
     *
     * @return the value of dbo.document_event.event_date
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public Date getEventDate() {
        return eventDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.event_date
     *
     * @param eventDate the value for dbo.document_event.event_date
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setEventDate(Date eventDate) {
        this.eventDate = eventDate;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.document_id
     *
     * @return the value of dbo.document_event.document_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public String getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.document_id
     *
     * @param documentId the value for dbo.document_event.document_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setDocumentId(String documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.patient_id
     *
     * @return the value of dbo.document_event.patient_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.patient_id
     *
     * @param patientId the value for dbo.document_event.patient_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.first_name
     *
     * @return the value of dbo.document_event.first_name
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.first_name
     *
     * @param firstName the value for dbo.document_event.first_name
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.last_name
     *
     * @return the value of dbo.document_event.last_name
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.last_name
     *
     * @param lastName the value for dbo.document_event.last_name
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.ssn
     *
     * @return the value of dbo.document_event.ssn
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.ssn
     *
     * @param ssn the value for dbo.document_event.ssn
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setSsn(String ssn) {
        this.ssn = ssn;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.dob
     *
     * @return the value of dbo.document_event.dob
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public String getDob() {
        return dob;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.dob
     *
     * @param dob the value for dbo.document_event.dob
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setDob(String dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column dbo.document_event.med_unit_id
     *
     * @return the value of dbo.document_event.med_unit_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public Integer getMedUnitId() {
        return medUnitId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column dbo.document_event.med_unit_id
     *
     * @param medUnitId the value for dbo.document_event.med_unit_id
     *
     * @ibatorgenerated Fri May 21 20:55:48 MDT 2010
     */
    public void setMedUnitId(Integer medUnitId) {
        this.medUnitId = medUnitId;
    }

	public String getUpdatedBy() {
		return updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	public void setEventTargetId(String eventTargetId) {
		this.eventTargetId = eventTargetId;
	}

	public String getEventTargetId() {
		return eventTargetId;
	}
}