module.exports = {
  'B B': 'Better Barbituates',
  'WC': 'White Count - Total white blood cells: All the white cell types are given as a percentage and as an absolute number per litre.',
  'Po':  'by mouth',
  'IM':  'intramuscular (in muscle)',
  'Subq':  'subcutaneous (under the skin)',
  'Q': 'every',
  'IV':  'intravenous (through the vein)',
  'Cap': 'capsule',
  'EC':  'enteric coated',
  'Tab':  'tablet',
  'AC':   'before meals',
  'PC':   'after meals',
  'Gtt':  'drops',
  'OD':   'right eye',
  'OS':   'left eye',
  's/p':  'status post(after)',
  'gm':   'grams',
  'mg':   'milligrams',
  'meq':  'milliequivalents',
  'IVPB':   'intravenous piggyback',
  'Oint':   'ointment',
  'Soln':   'solution',
  'INHL':   'inhaler',
  'Ml':   'milliliter',
  'Min.':   'minutes',
  'UA':   'urinalysis',
  'CBC':  'complete blood count',
  'C&S':  'culture & sensitivity',
  'Hgb':  'hemoglobin',
  'Hct':  'hematocrit',
  'BP':   'blood pressure',
  'HR':   'heart rate',
  'STAT':   'immediately',
  'CXR':  'chest x-ray',
  'MRI':  'magnetic resonance imagery',
  'CT':   'computerized axial tomography',
  'US':   'ultrasound',
  'TEMP':   'temperature',
  '&le;':   'less than or equal to',
  '&ge;':   'greater than or equal to',
  'Inj':  'injection',
  'Imaging':  'X-Ray',
  'Pending':  'those orders waiting to be signed by Dr.',
  'Active':   'those orders waiting to be carried out',
  'ASAP':   'As soon as possible',
  'PA&LAT':   'posterior/anterior & lateral views',
  'Q4H':  'EVERY 4 HOURS',
  'Q6H':  'EVERY 6 HOURS',
  'Q8H':  'EVERY 8 HOURS',
  'QAM':  'EVERY MORNING',
  'QDAY':   'EVERY DAY',
  'BID':  'TWICE A DAY',
  'Q3H':  'EVERY 3 HOURS',
  'QPM':  'EVERY EVENING',
  'Q12H':   'EVERY 12 HOURS',
  'TID':  'THREE TIMES A DAY',
  'QID':  'FOUR TIMES A DAY',
  'QOD':  'EVERY OTHER DAY',
  'QHS':  'AT BEDTIME',
  'Q24H':   'EVERY 24 HOURS',
  'Q2H':  'EVERY 2 HOURS',
  'WEEKLY':   'WEEKLY',
  'HS':   'AT BEDTIME',
  'QDAY-DIG':   'EVERY DAY AT 1 PM',
  'Q2WEEK':   'EVERY TWO WEEKS',
  'QDAY-WARF':  'EVERY DAY AT 1 PM'
};
