package gov.va.medora.mdws.emrsvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 05 13:15:55 MST 2011
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://mdws.medora.va.gov/EmrSvc", name = "EmrSvcHttpPost")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface EmrSvcHttpPost {

    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedHospitalLocationArray getWards();

    @WebResult(name = "TaggedRadiologyReportArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedRadiologyReportArrays getRadiologyReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedCytologyRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedCytologyRptArrays getCytologyReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedVisitArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedVisitArray getVisits(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getCrisisNotes(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedSurgeryReportArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedSurgeryReportArrays getSurgeryReports();

    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedMedicationArrays getIvMeds();

    @WebResult(name = "TaggedOrderArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedOrderArrays getAllOrders();

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getConfidentiality();

    @WebResult(name = "TaggedSurgeryReportArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedSurgeryReportArrays getSurgeryReportsWithText();

    @WebResult(name = "TaggedVitalSignSetArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedVitalSignSetArrays getVitalSigns();

    @WebResult(name = "TaggedChemHemRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedChemHemRptArrays getChemHemReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getMedsAdminHx(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getImmunizations(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO closeNote(
        @WebParam(partName = "noteIEN", name = "noteIEN", targetNamespace = "")
        java.lang.String noteIEN,
        @WebParam(partName = "consultIEN", name = "consultIEN", targetNamespace = "")
        java.lang.String consultIEN
    );

    @WebResult(name = "PatientTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public PatientTO select(
        @WebParam(partName = "DFN", name = "DFN", targetNamespace = "")
        java.lang.String dfn
    );

    @WebResult(name = "TaggedProblemArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedProblemArrays getProblemList(
        @WebParam(partName = "type", name = "type", targetNamespace = "")
        java.lang.String type
    );

    @WebResult(name = "TaggedSurgicalPathologyRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedSurgicalPathologyRptArrays getSurgicalPathologyReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedMicrobiologyRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedMicrobiologyRptArrays getMicrobiologyReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getExpandedAdtReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedIcdRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedIcdRptArrays getIcdProceduresReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedMedicationArrays getAllMeds();

    @WebResult(name = "UserArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public UserArray cprsUserLookup(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getMedsAdminLog(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray visit(
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "sitelist", name = "sitelist", targetNamespace = "")
        java.lang.String sitelist,
        @WebParam(partName = "userSitecode", name = "userSitecode", targetNamespace = "")
        java.lang.String userSitecode,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(partName = "DUZ", name = "DUZ", targetNamespace = "")
        java.lang.String duz,
        @WebParam(partName = "SSN", name = "SSN", targetNamespace = "")
        java.lang.String ssn,
        @WebParam(partName = "context", name = "context", targetNamespace = "")
        java.lang.String context
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getTreatingSpecialtyReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "SiteArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public SiteArray setupMultiSiteQuery(
        @WebParam(partName = "appPwd", name = "appPwd", targetNamespace = "")
        java.lang.String appPwd
    );

    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedHospitalLocationArray getLocations(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target,
        @WebParam(partName = "direction", name = "direction", targetNamespace = "")
        java.lang.String direction
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getFutureClinicVisitsReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedText isOneVisitNote(
        @WebParam(partName = "noteDefinitionIEN", name = "noteDefinitionIEN", targetNamespace = "")
        java.lang.String noteDefinitionIEN,
        @WebParam(partName = "noteTitle", name = "noteTitle", targetNamespace = "")
        java.lang.String noteTitle,
        @WebParam(partName = "visitString", name = "visitString", targetNamespace = "")
        java.lang.String visitString
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO isCosignerRequired(
        @WebParam(partName = "noteDefinitionIEN", name = "noteDefinitionIEN", targetNamespace = "")
        java.lang.String noteDefinitionIEN,
        @WebParam(partName = "authorDUZ", name = "authorDUZ", targetNamespace = "")
        java.lang.String authorDUZ
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getCytopathologyReports();

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO getSurgeryReportText(
        @WebParam(partName = "siteId", name = "siteId", targetNamespace = "")
        java.lang.String siteId,
        @WebParam(partName = "rptId", name = "rptId", targetNamespace = "")
        java.lang.String rptId
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getElectronMicroscopyReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO isValidEsig(
        @WebParam(partName = "esig", name = "esig", targetNamespace = "")
        java.lang.String esig
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray issueConfidentialityBulletin();

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getDischargesReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO getMedicationDetail(
        @WebParam(partName = "siteId", name = "siteId", targetNamespace = "")
        java.lang.String siteId,
        @WebParam(partName = "medId", name = "medId", targetNamespace = "")
        java.lang.String medId
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getOutpatientEncounterReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getBloodTransfusionReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedHospitalLocationArray getClinics(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target
    );

    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedPatientArray getPatientsByWard(
        @WebParam(partName = "wardId", name = "wardId", targetNamespace = "")
        java.lang.String wardId
    );

    @WebResult(name = "PatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public PatientArray nptLookup(
        @WebParam(partName = "SSN", name = "SSN", targetNamespace = "")
        java.lang.String ssn
    );

    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedNoteArrays getDischargeSummaries(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nNotes", name = "nNotes", targetNamespace = "")
        java.lang.String nNotes
    );

    @WebResult(name = "RegionArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public RegionArray getVHA();

    @WebResult(name = "PatientRecordFlagArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public PatientRecordFlagArray getPrfNoteActions(
        @WebParam(partName = "noteDefinitionIEN", name = "noteDefinitionIEN", targetNamespace = "")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getPastClinicVisitsReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedText isSurgeryNote(
        @WebParam(partName = "noteDefinitionIEN", name = "noteDefinitionIEN", targetNamespace = "")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO patientInquiry();

    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedMedicationArrays getOtherMeds();

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getBloodBankReports();

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO getFacadeVersion();

    @WebResult(name = "TaggedAllergyArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedAllergyArrays getAllergies();

    @WebResult(name = "string", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public java.lang.String getVersion();

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getNoteTitles(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target,
        @WebParam(partName = "direction", name = "direction", targetNamespace = "")
        java.lang.String direction
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO getAppointmentText(
        @WebParam(partName = "siteId", name = "siteId", targetNamespace = "")
        java.lang.String siteId,
        @WebParam(partName = "apptId", name = "apptId", targetNamespace = "")
        java.lang.String apptId
    );

    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedText getSpecialties();

    @WebResult(name = "OrderTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public OrderTO writeSimpleOrderByPolicy(
        @WebParam(partName = "providerDUZ", name = "providerDUZ", targetNamespace = "")
        java.lang.String providerDUZ,
        @WebParam(partName = "esig", name = "esig", targetNamespace = "")
        java.lang.String esig,
        @WebParam(partName = "locationIEN", name = "locationIEN", targetNamespace = "")
        java.lang.String locationIEN,
        @WebParam(partName = "orderIEN", name = "orderIEN", targetNamespace = "")
        java.lang.String orderIEN,
        @WebParam(partName = "startDate", name = "startDate", targetNamespace = "")
        java.lang.String startDate
    );

    @WebResult(name = "TaggedConsultArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedConsultArrays getConsultsForPatient();

    @WebResult(name = "NoteResultTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public NoteResultTO writeNote(
        @WebParam(partName = "titleIEN", name = "titleIEN", targetNamespace = "")
        java.lang.String titleIEN,
        @WebParam(partName = "encounterString", name = "encounterString", targetNamespace = "")
        java.lang.String encounterString,
        @WebParam(partName = "text", name = "text", targetNamespace = "")
        java.lang.String text,
        @WebParam(partName = "authorDUZ", name = "authorDUZ", targetNamespace = "")
        java.lang.String authorDUZ,
        @WebParam(partName = "cosignerDUZ", name = "cosignerDUZ", targetNamespace = "")
        java.lang.String cosignerDUZ,
        @WebParam(partName = "consultIEN", name = "consultIEN", targetNamespace = "")
        java.lang.String consultIEN,
        @WebParam(partName = "prfIEN", name = "prfIEN", targetNamespace = "")
        java.lang.String prfIEN
    );

    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedNoteArrays getNotesWithText(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nNotes", name = "nNotes", targetNamespace = "")
        java.lang.String nNotes
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getBloodAvailabilityReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO isPrfNote(
        @WebParam(partName = "noteDefinitionIEN", name = "noteDefinitionIEN", targetNamespace = "")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "SiteTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public SiteTO addDataSource(
        @WebParam(partName = "id", name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(partName = "name", name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(partName = "datasource", name = "datasource", targetNamespace = "")
        java.lang.String datasource,
        @WebParam(partName = "port", name = "port", targetNamespace = "")
        java.lang.String port,
        @WebParam(partName = "modality", name = "modality", targetNamespace = "")
        java.lang.String modality,
        @WebParam(partName = "protocol", name = "protocol", targetNamespace = "")
        java.lang.String protocol,
        @WebParam(partName = "region", name = "region", targetNamespace = "")
        java.lang.String region
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getCareTeamReports();

    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedMedicationArrays getImoMeds();

    @WebResult(name = "TaggedIcdRptArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedIcdRptArrays getIcdSurgeryReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getDischargeDiagnosisReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "DataSourceArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public DataSourceArray connect(
        @WebParam(partName = "sitelist", name = "sitelist", targetNamespace = "")
        java.lang.String sitelist
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getAutopsyReports();

    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedNoteArrays getUnsignedNotes(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nNotes", name = "nNotes", targetNamespace = "")
        java.lang.String nNotes
    );

    @WebResult(name = "TaggedAppointmentArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedAppointmentArrays getAppointments();

    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedMedicationArrays getUnitDoseMeds();

    @WebResult(name = "TaggedInpatientStayArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedInpatientStayArray getAdmissions();

    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedPatientArray getPatientsBySpecialty(
        @WebParam(partName = "specialtyId", name = "specialtyId", targetNamespace = "")
        java.lang.String specialtyId
    );

    @WebResult(name = "PatientTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public PatientTO getDemographics();

    @WebResult(name = "TaggedHospitalLocationArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedHospitalLocationArray getHospitalLocations(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target,
        @WebParam(partName = "direction", name = "direction", targetNamespace = "")
        java.lang.String direction
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getCompAndPenReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO getNote(
        @WebParam(partName = "siteId", name = "siteId", targetNamespace = "")
        java.lang.String siteId,
        @WebParam(partName = "noteId", name = "noteId", targetNamespace = "")
        java.lang.String noteId
    );

    @WebResult(name = "TaggedVitalSignArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedVitalSignArrays getLatestVitalSigns();

    @WebResult(name = "TaggedPatientArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedPatientArrays match(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO isConsultNote(
        @WebParam(partName = "noteDefinitionIEN", name = "noteDefinitionIEN", targetNamespace = "")
        java.lang.String noteDefinitionIEN
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray disconnectRemoteSites();

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getClinicalWarnings(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray disconnect();

    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedNoteArrays getUncosignedNotes(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nNotes", name = "nNotes", targetNamespace = "")
        java.lang.String nNotes
    );

    @WebResult(name = "TaggedMedicationArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedMedicationArrays getOutpatientMeds();

    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedPatientArray getPatientsByTeam(
        @WebParam(partName = "teamId", name = "teamId", targetNamespace = "")
        java.lang.String teamId
    );

    @WebResult(name = "PatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public PatientArray mpiLookup(
        @WebParam(partName = "SSN", name = "SSN", targetNamespace = "")
        java.lang.String ssn
    );

    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedText getTeams();

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TextTO signNote(
        @WebParam(partName = "noteIEN", name = "noteIEN", targetNamespace = "")
        java.lang.String noteIEN,
        @WebParam(partName = "userDUZ", name = "userDUZ", targetNamespace = "")
        java.lang.String userDUZ,
        @WebParam(partName = "esig", name = "esig", targetNamespace = "")
        java.lang.String esig
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getAdvanceDirectives(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "UserTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public UserTO login(
        @WebParam(partName = "username", name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "context", name = "context", targetNamespace = "")
        java.lang.String context
    );

    @WebResult(name = "PersonsTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public PersonsTO cprsLaunch(
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "sitecode", name = "sitecode", targetNamespace = "")
        java.lang.String sitecode,
        @WebParam(partName = "DUZ", name = "DUZ", targetNamespace = "")
        java.lang.String duz,
        @WebParam(partName = "DFN", name = "DFN", targetNamespace = "")
        java.lang.String dfn
    );

    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedPatientArray getPatientsByProvider(
        @WebParam(partName = "duz", name = "duz", targetNamespace = "")
        java.lang.String duz
    );

    @WebResult(name = "RadiologyReportTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public RadiologyReportTO getImagingReport(
        @WebParam(partName = "SSN", name = "SSN", targetNamespace = "")
        java.lang.String ssn,
        @WebParam(partName = "accessionNumber", name = "accessionNumber", targetNamespace = "")
        java.lang.String accessionNumber
    );

    @WebResult(name = "SiteArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public SiteArray setVha(
        @WebParam(partName = "sitesFileName", name = "sitesFileName", targetNamespace = "")
        java.lang.String sitesFileName
    );

    @WebResult(name = "TaggedNoteArrays", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedNoteArrays getSignedNotes(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nNotes", name = "nNotes", targetNamespace = "")
        java.lang.String nNotes
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getTransfersReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getAdmissionsReports(
        @WebParam(partName = "fromDate", name = "fromDate", targetNamespace = "")
        java.lang.String fromDate,
        @WebParam(partName = "toDate", name = "toDate", targetNamespace = "")
        java.lang.String toDate,
        @WebParam(partName = "nrpts", name = "nrpts", targetNamespace = "")
        java.lang.String nrpts
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedTextArray getOutpatientRxProfile();

    @WebResult(name = "TaggedPatientArray", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public TaggedPatientArray getPatientsByClinic(
        @WebParam(partName = "clinicId", name = "clinicId", targetNamespace = "")
        java.lang.String clinicId
    );

    @WebResult(name = "RegionTO", targetNamespace = "http://mdws.medora.va.gov/EmrSvc", partName = "Body")
    @WebMethod
    public RegionTO getVISN(
        @WebParam(partName = "regionId", name = "regionId", targetNamespace = "")
        java.lang.String regionId
    );
}
