package gov.va.medora.mdws.querysvc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.ParameterStyle;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Wed Jan 05 13:14:31 MST 2011
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://mdws.medora.va.gov/QuerySvc", name = "QuerySvcHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface QuerySvcHttpGet {

    @WebResult(name = "TaggedPatientArrays", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TaggedPatientArrays match(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target
    );

    @WebResult(name = "PatientTO", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public PatientTO select(
        @WebParam(partName = "DFN", name = "DFN", targetNamespace = "")
        java.lang.String dfn
    );

    @WebResult(name = "UserTO", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public UserTO login(
        @WebParam(partName = "username", name = "username", targetNamespace = "")
        java.lang.String username,
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "context", name = "context", targetNamespace = "")
        java.lang.String context
    );

    @WebResult(name = "UserArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public UserArray cprsUserLookup(
        @WebParam(partName = "target", name = "target", targetNamespace = "")
        java.lang.String target
    );

    @WebResult(name = "DataSourceArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public DataSourceArray connect(
        @WebParam(partName = "sitelist", name = "sitelist", targetNamespace = "")
        java.lang.String sitelist
    );

    @WebResult(name = "RegionArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public RegionArray getVHA();

    @WebResult(name = "UserTO", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public UserTO userLookup(
        @WebParam(partName = "duz", name = "duz", targetNamespace = "")
        java.lang.String duz
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TextTO getVariableValue(
        @WebParam(partName = "arg", name = "arg", targetNamespace = "")
        java.lang.String arg
    );

    @WebResult(name = "TextArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TextArray ddrLister(
        @WebParam(partName = "file", name = "file", targetNamespace = "")
        java.lang.String file,
        @WebParam(partName = "iens", name = "iens", targetNamespace = "")
        java.lang.String iens,
        @WebParam(partName = "fields", name = "fields", targetNamespace = "")
        java.lang.String fields,
        @WebParam(partName = "flags", name = "flags", targetNamespace = "")
        java.lang.String flags,
        @WebParam(partName = "maxrex", name = "maxrex", targetNamespace = "")
        java.lang.String maxrex,
        @WebParam(partName = "from", name = "from", targetNamespace = "")
        java.lang.String from,
        @WebParam(partName = "part", name = "part", targetNamespace = "")
        java.lang.String part,
        @WebParam(partName = "xref", name = "xref", targetNamespace = "")
        java.lang.String xref,
        @WebParam(partName = "screen", name = "screen", targetNamespace = "")
        java.lang.String screen,
        @WebParam(partName = "identifier", name = "identifier", targetNamespace = "")
        java.lang.String identifier
    );

    @WebResult(name = "SiteArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public SiteArray setVha(
        @WebParam(partName = "sitesFileName", name = "sitesFileName", targetNamespace = "")
        java.lang.String sitesFileName
    );

    @WebResult(name = "string", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public java.lang.String getVersion();

    @WebResult(name = "UserTO", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public UserTO visitSite(
        @WebParam(partName = "pwd", name = "pwd", targetNamespace = "")
        java.lang.String pwd,
        @WebParam(partName = "sitecode", name = "sitecode", targetNamespace = "")
        java.lang.String sitecode,
        @WebParam(partName = "userSitecode", name = "userSitecode", targetNamespace = "")
        java.lang.String userSitecode,
        @WebParam(partName = "userName", name = "userName", targetNamespace = "")
        java.lang.String userName,
        @WebParam(partName = "DUZ", name = "DUZ", targetNamespace = "")
        java.lang.String duz,
        @WebParam(partName = "SSN", name = "SSN", targetNamespace = "")
        java.lang.String ssn,
        @WebParam(partName = "context", name = "context", targetNamespace = "")
        java.lang.String context
    );

    @WebResult(name = "TaggedText", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TaggedText siteHasPatch(
        @WebParam(partName = "patchId", name = "patchId", targetNamespace = "")
        java.lang.String patchId
    );

    @WebResult(name = "SiteTO", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public SiteTO addDataSource(
        @WebParam(partName = "id", name = "id", targetNamespace = "")
        java.lang.String id,
        @WebParam(partName = "name", name = "name", targetNamespace = "")
        java.lang.String name,
        @WebParam(partName = "datasource", name = "datasource", targetNamespace = "")
        java.lang.String datasource,
        @WebParam(partName = "port", name = "port", targetNamespace = "")
        java.lang.String port,
        @WebParam(partName = "modality", name = "modality", targetNamespace = "")
        java.lang.String modality,
        @WebParam(partName = "protocol", name = "protocol", targetNamespace = "")
        java.lang.String protocol,
        @WebParam(partName = "region", name = "region", targetNamespace = "")
        java.lang.String region
    );

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TaggedTextArray disconnect();

    @WebResult(name = "TextArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TextArray ddrGetsEntry(
        @WebParam(partName = "file", name = "file", targetNamespace = "")
        java.lang.String file,
        @WebParam(partName = "iens", name = "iens", targetNamespace = "")
        java.lang.String iens,
        @WebParam(partName = "flds", name = "flds", targetNamespace = "")
        java.lang.String flds,
        @WebParam(partName = "flags", name = "flags", targetNamespace = "")
        java.lang.String flags
    );

    @WebResult(name = "TextTO", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TextTO getFacadeVersion();

    @WebResult(name = "TaggedTextArray", targetNamespace = "http://mdws.medora.va.gov/QuerySvc", partName = "Body")
    @WebMethod
    public TaggedTextArray sitesHavePatch(
        @WebParam(partName = "sitelist", name = "sitelist", targetNamespace = "")
        java.lang.String sitelist,
        @WebParam(partName = "patchId", name = "patchId", targetNamespace = "")
        java.lang.String patchId
    );
}
